export default function UkDisclaimer() {
  return (
    <>
      <h2>CREATION RIGHTS</h2>
      <h2>
        <strong>UK DISCLAIMERS SCHEDULE</strong>
      </h2>

      <p>Effective date: May 2026 | Last updated: 18 May 2026</p>

      <h2>1. Purpose and priority</h2>
      <p>
        This Schedule is incorporated into the UK Website Terms and Conditions,
        UK services terms, order forms, schedules, addenda, metadata workflows,
        publishing flows, payout flows, and any product screen that references
        it. If there is a conflict with an executed order form or mandatory law,
        that order form or mandatory law controls to the extent of the conflict.
      </p>

      <h2>2. Platform provider only</h2>
      <p>
        Creation Rights provides software, workflow, asset-management,
        rights-recording, metadata, clause-code, consent, approval,
        transaction-support, audit, and payout-instruction tools for creative
        industry workflows. Creation Rights does not provide legal, tax,
        accounting, financial, investment, valuation, insurance, regulatory,
        employment, union, talent agency, collective management,
        rights-clearance guarantor, payment institution, escrow, banking,
        trustee, fiduciary, or money transmission services. Creation Rights is
        not a law firm, solicitor, barrister, tax adviser, accountant, financial
        adviser, investment adviser, insurer, collective management
        organisation, talent agency.
      </p>

      <h2>3. User responsibility</h2>
      <p>
        Users remain responsible for obtaining, maintaining, and proving all
        rights, consents, releases, licences, approvals, assignments, waivers,
        tax documentation, advertising disclosures, privacy notices, biometric
        consents, union or guild permissions, and other permissions required for
        their intended creation, upload, storage, licensing, sale, publication,
        distribution, promotion, training, AI processing, synthetic generation,
        usage, renewal, transfer, payout, or commercial exploitation of any
        Creative Asset.
      </p>

      <h2>4. No legal, tax, financial, or professional advice</h2>
      <p>
        Templates, clauses, order forms, metadata codes, AI outputs, risk
        scores, risk flags, rights checks, payout calculations, refund
        calculations, and platform recommendations are operational tools only.
        They do not replace advice from qualified legal, tax, financial,
        accounting, insurance, regulatory, employment, union, or other
        professionals. Creator declarations regarding originality, rights
        ownership, moral rights, work-for-hire status, and AI provenance are
        user-provided statements captured in metadata. The Platform does not
        verify the legal accuracy of these declarations.
      </p>
      <p>
        Creator declarations regarding originality, rights ownership, moral
        rights, work-for-hire status, and AI provenance are user-provided
        statements captured in metadata. The Platform does not verify the legal
        accuracy of these declarations.
      </p>
      <p>
        The automated clearance output is generated by CR Agents based on rules,
        metadata, and user-provided information. It is not a legal audit, due
        diligence review, or opinion on legal sufficiency.
      </p>
      <p>
        Modular agreement templates are starting points populated with
        user-provided variables, not bespoke legal instruments. Consent
        mechanisms are capture tools, not guarantees of legal validity.
      </p>
      <p>
        Users must consult qualified attorneys before executing Order Forms,
        granting IP or NILP licences, waiving moral rights, making work-for-hire
        elections, entering cross-border transactions, or processing Biometric
        Data.
      </p>

      <h2>5. Not escrow, bank, payment institution, wallet, or fiduciary</h2>
      <p>
        Creation Rights is a technology platform. The Platform provides
        technology services: workflow management, modular agreement templates,
        content provenance tracking, NILP® protection, metadata infrastructure,
        Risk Scores, Transaction Clearance, payout gates, and payment routing
        via Stripe. Creation Rights is not a bank, escrow agent, payment
        institution, financial institution, electronic money institution, money
        transmitter, stored-value provider, custodian, law firm, solicitors&apos;
        practice, trustee, fiduciary, wallet provider, tax adviser, accountant,
        talent agency, employment agency, casting service, insurance provider,
        securities exchange, investment platform, or crowdfunding service. Funds
        movement, payment processing, onboarding, refunds, chargebacks,
        reversals, reserves, and payouts may be handled by third-party
        processors and banks under their own terms. Royalty calculations,
        clawback, escrow. Escrow is a commercial convenience, not a regulated
        escrow service. No employment, joint venture, partnership, or agency
        relationship is created between the Platform and any User.
      </p>

      <h2>6. No securities, fan ownership, investment, or passive income</h2>
      <p>
        Nothing in the services is intended to offer or sell securities,
        investment contracts, fractional ownership, fan equity, dividends,
        passive income products, speculative profit interests, or regulated
        financial promotions. Creative transactions are contractual commercial
        arrangements unless expressly documented otherwise in a separate
        counsel-reviewed agreement. Creative assets, NILP-style permissions,
        royalties, usage fees, renewals, campaign payments, and payout splits
        are contractual commercial arrangements only, unless expressly
        documented otherwise in a separate legally reviewed agreement.
      </p>

      <h2>7. No rights ownership or clearance guarantee</h2>
      <p>
        Creation Rights does not guarantee that any user owns, controls, or has
        cleared content, music, footage, data, prompts, outputs, software,
        trademarks, design rights, trade dress, passing off risk, location
        releases, property releases, or third-party permissions designs,
        locations, property, performance, image, likeness, voice, persona,
        database rights, confidential information, or third-party rights for any
        Creative Asset. Users are responsible for all rights, licences,
        consents, releases, approvals, waivers, and permissions required for
        their intended use. Creation Rights does not guarantee that any Creative
        Asset, licence, rights grant, NILP use, identity use, AI output,
        synthetic media asset, prompt, dataset, music track, video, image,
        design, work, campaign, channel, territory, publication, distribution,
        payout, renewal, or transaction is lawful, cleared, enforceable,
        payable, publishable, commercially suitable, or free from third-party
        claims.
      </p>
      <p>
        A platform status such as approved, cleared, ready, low risk, payable,
        payout eligible, publishable, compliant, or similar only means that the
        applicable platform workflow conditions identified by Creation Rights at
        that time appear to have been satisfied. It does not mean that the
        asset, transaction, licence, campaign, content, likeness use, AI use,
        disclosure, payout, or publication is free from legal, tax, regulatory,
        commercial, reputational, or third-party risk.
      </p>

      <h2>
        8. Metadata, clause-code, cross-sector, rights classification, and
        decision-support disclaimer
      </h2>
      <p>
        A metadata code is not a legal clearance certificate. Metadata codes,
        clause references, sector classifications, asset classifications, legal
        triggers, rights classifications, risk indicators, sector
        classifications, risk scores, consent flags, payout gates, usage rules,
        expiry indicators, renewal triggers, publishing checks, publishing
        statuses are workflow and audit tools only and audit references are
        operational and decision-support tools only. They do not constitute
        legal advice, tax advice, rights verification, ownership verification,
        clearance confirmation, compliance certification, valuation advice, or a
        guarantee that any creative asset, use, transaction, licence, payout,
        publication, campaign, AI output, synthetic media asset, or cross-sector
        asset is lawful, cleared, enforceable, payable, publishable, or
        commercially suitable. They may be incomplete or inaccurate if user
        inputs, third-party data, connected services, uploaded files, or
        automated classifications are incomplete, inaccurate, outdated,
        misleading, or unlawful.
      </p>
      <p>
        Cross-sector assets may combine advertising, music, film, television,
        gaming, fashion, beauty, sports, publishing, editorial, photography,
        visual art, software, prompts, datasets, property media, live events,
        cultural heritage, or product packaging rights. A clearance decision for
        one sector, channel, territory, or term does not imply clearance for any
        other sector, channel, territory, term, renewal, derivative use, AI
        use, paid media use, or resale use.
      </p>

      <h2>9. No automated clearance guarantee</h2>
      <p>
        Any automated, AI-assisted, rules-based, metadata-based, or
        clause-code-based review is not a substitute for independent legal, tax,
        rights, compliance, accounting, financial, or professional review. A
        status such as cleared, approved, ready, low risk, payout eligible,
        publishable, or similar only means that the platform workflow conditions
        identified at that time appear to have been satisfied. It does not mean
        the asset, transaction, campaign, licence, content, likeness use, AI
        use, disclosure, payout, or publication is free from legal, commercial,
        tax, regulatory, reputational, or third-party risk.
      </p>

      <h2>10. AI and synthetic media disclaimer</h2>
      <p>
        AI-generated content, AI-assisted editing, AI training, model
        fine-tuning, voice clone, synthetic likeness, digital replica, avatar,
        prompt reuse, voice clone, persona simulation, avatar generation, or
        biometric recognition, and agent output features may be inaccurate,
        incomplete, unlawful, infringing, biased, or unsuitable and may require
        separate, express, transaction-specific consent. General account
        creation, general upload, or general acceptance of platform terms does
        not by itself grant permission for AI training, synthetic likeness use,
        voice cloning, persona simulation, or biometric processing. Users
        declare AI provenance The Platform does not verify this declaration.
        Users are responsible for reviewing outputs and obtaining required rights
        and permissions. AI outputs may be factually incorrect, misleading, or
        defamatory. Users deploying AI content are responsible for human review
        before publication.
      </p>

      <h2>
        11. NILP-style identity, moral rights, performer, and
        publicity-equivalent disclaimer
      </h2>
      <p>
        UK law does not provide a single US-style right of publicity.
        Identity-related uses may implicate passing off, privacy, data
        protection, confidentiality, performer rights, moral rights, copyright,
        contract, advertising rules, and other rights. A NILP or identity
        metadata code does not prove that any name, image, likeness, persona,
        voice, performance, signature, avatar, digital replica, or biometric
        rights have been properly cleared. The User declares NILP inventory. The
        Platform does not warrant: (a) the consent mechanism satisfies any
        particular state statute; (b) NILP Rights are valid and enforceable; (c)
        the scope of use is sufficient; (d) posthumous rights are valid under
        the applicable state. Creation Rights does not guarantee that UK moral
        rights, performer property rights, performer non-property rights,
        recording consents, broadcast consents, or waivers have been validly
        obtained. Any waiver, consent, licence, assignment, or release must be
        express, specific, and properly recorded where required.
      </p>

      <h2>12. Biometric and privacy disclaimer</h2>
      <p>
        Facial, voice, gait, identity verification, or other biometric features
        may involve special category data where used to uniquely identify a
        person. Users must not upload or process such data without required
        lawful basis, explicit consent where needed, notices, retention rules,
        deletion rules, and authority. Where a feature processes facial geometry,
        voiceprints, likeness data, identity verification data, biometric
        identifiers, or other sensitive data, Creation Rights will process such
        data only as described in the applicable privacy notice, consent flow,
        biometric notice, retention schedule, and data processing terms. Users
        must not upload or process special category data or biometric data
        unless they have the required lawful basis, explicit consent where
        required, notices, authority, and safeguards.
      </p>

      <h2>13. Advertising disclosure disclaimer</h2>
      <p>
        Brands, agencies, creators, affiliates, and other campaign participants
        are responsible for ensuring that paid, sponsored, gifted, affiliate,
        advertorial, influencer, endorsement, and other material connection
        disclosures are clear, timely, platform-appropriate, and compliant with
        applicable law, ASA/CAP requirements, platform rules, and sector rules.
        Metadata prompts or disclosure fields do not guarantee advertising
        compliance. Workflow prompts for #ad, sponsorship, gifted product,
        affiliate links, AI-generated labels, or material-connection disclosures
        do not guarantee compliance with ASA/CAP, platform, consumer, sector, or
        other advertising rules. Brands, agencies, creators, publishers, and
        other participants remain responsible for compliant disclosures.
      </p>

      <h2>14. Payout, reserve, refund, and reversal disclaimer</h2>
      <p>
        Payouts are not automatic and are not guaranteed by account creation,
        content upload, asset upload, invoice creation, deal creation, campaign
        approval, payment initiation, metadata status, publication approval,
        payment initiation, or any platform label. Payouts may be delayed,
        reduced, reserved, reversed, offset, or withheld until applicable gates
        are satisfied, including payment success, rights and NILP consent,
        deliverable approval, tax documentation, sanctions and risk checks,
        fraud review, dispute holds, reserve requirements, processor rules, and
        applicable law. Refunds, kill fees, reserves, chargebacks, reversals,
        offsets, recoupments, and repayment obligations are governed by the
        applicable Terms, Order Form, Payout Schedule, Refund/Reversal Schedule,
        processor rules, and applicable law. A ledger entry, metadata status, or
        payout eligibility status does not remove processor reversal rights,
        dispute rights, tax holds, sanctions holds, or reserve requirements.
      </p>

      <h2>15. Automated review</h2>
      <p>
        Any automated, AI-assisted, rules-based, metadata-based, or
        clause-code-based review is not a substitute for independent legal, tax,
        rights, compliance, accounting, financial, or professional review.
        Automated outputs may be incomplete, inaccurate, biased, outdated, or
        inappropriate for the relevant legal context.
      </p>

      <h2>16. Third-party services disclaimer</h2>
      <p>
        We do not control third-party processors, banks, integrations, AI
        providers, analytics providers, cloud services, identity providers, tax
        providers, or collaboration tools. Third-party availability, terms,
        fees, decisions, data handling, and errors may affect workflows.
      </p>

      <h2>17. Non-excludable liability carve-out</h2>
      <p>
        Nothing in these terms, any schedule, any order form, any role terms,
        any policy, or any other agreement incorporated by reference excludes,
        limits, restricts, waives, or caps any liability that cannot lawfully be
        excluded, limited, restricted, waived, or capped under applicable law.
        Without limiting the above, nothing excludes, limits, restricts, waives,
        or caps liability for fraud or fraudulent misrepresentation, death or
        personal injury caused by negligence, gross negligence, wilful
        misconduct, any intentional or dishonest act, or any liability that
        applicable consumer, data protection, payment, intellectual property,
        performer rights, privacy, biometric, employment, tax, sanctions,
        anti-bribery, anti-money laundering, or other mandatory law does not
        permit to be excluded, limited, restricted, waived, or capped.
      </p>

      <h2>Product and Website Short-Form Notices</h2>
      <h3>Short-form notices for product UI</h3>

      <table>
        <thead>
          <tr>
            <th>Product location</th>
            <th>Short-form notice</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Footer notice</td>
            <td>
              Creation Rights provides software, workflow, rights-recording,
              metadata, and payout-instruction tools. We are not a law firm, tax
              adviser, payment institution, bank, escrow agent, trustee,
              fiduciary, securities platform, talent agency, or insurer.
            </td>
          </tr>
          <tr>
            <td>Upload notice</td>
            <td>
              You confirm that you have the rights, consents, releases,
              licences, and authority required to upload and use this asset. A
              metadata code is not a legal clearance certificate.
            </td>
          </tr>
          <tr>
            <td>AI/NILP notice</td>
            <td>
              AI training, synthetic likeness, voice clone, digital replica,
              persona simulation, or biometric processing requires separate
              express consent where applicable.
            </td>
          </tr>
          <tr>
            <td>Payout notice</td>
            <td>
              Payout eligibility is not a payout guarantee. Payouts remain
              subject to payment success, tax documentation, sanctions/risk
              checks, disputes, reserves, reversals, processor rules, and
              applicable law.
            </td>
          </tr>
          <tr>
            <td>Publishing notice</td>
            <td>
              Ready to publish means platform workflow conditions appear complete
              at this time. It does not guarantee legal clearance, advertising
              compliance, rights ownership, or absence of third-party claims.
            </td>
          </tr>
        </tbody>
      </table>

      <h2>Workflow Short-Form Notices</h2>

      <table>
        <thead>
          <tr>
            <th>Workflow location</th>
            <th>Short-form notice</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Asset upload</td>
            <td>
              You confirm you have the rights, consents, releases, and authority
              required to upload and use this asset.
            </td>
          </tr>
          <tr>
            <td>Metadata status</td>
            <td>A metadata code is not a legal clearance certificate.</td>
          </tr>
          <tr>
            <td>AI/NILP consent</td>
            <td>
              AI training, synthetic likeness, voice clone, digital replica, and
              persona simulation require separate express consent.
            </td>
          </tr>
          <tr>
            <td>Publishing approval</td>
            <td>
              Ready to publish means platform workflow checks appear complete. It
              is not a legal guarantee.
            </td>
          </tr>
          <tr>
            <td>Payout page</td>
            <td>
              Payout eligibility is subject to payment success, tax, rights,
              consent, sanctions/risk, dispute, reserve, processor rules, and
              law.
            </td>
          </tr>
        </tbody>
      </table>
    </>
  );
}
