import { cskillsImages } from "./images";

export type SkillPack = {
  slug: string;
  name: string;
  category: string;
  section: "featured" | "image-video" | "audio-voice" | "asset-metadata" | "rights-release";
  featured: boolean;
  image: string;
  outcome: string;
  ecosystem: string[];
  tags: string[];
  preview: string;
};

export const skillPacks: SkillPack[] = [
  // === Featured ===
  {
    slug: "ai-video-generation",
    name: "AI Video Generation Skill Pack",
    category: "Video",
    section: "featured",
    featured: true,
    image: cskillsImages.capabilities.productionAgentSkills,
    outcome: "Define approved use of video generation tools, source assets, likeness limits, review gates, evidence capture, and release checks.",
    ecosystem: ["Runway", "LTX", "fal.ai", "ComfyUI", "Adobe Firefly"],
    tags: ["video", "generation", "model", "likeness", "rights", "evidence", "release"],
    preview: "This pack defines which video generation tools are approved, what source assets can be used, what likeness and rights constraints apply, what review gates must be passed, and what evidence is captured before release.",
  },
  {
    slug: "release-proof",
    name: "Release Proof Skill Pack",
    category: "Release",
    section: "featured",
    featured: true,
    image: cskillsImages.core.creationRightsReadiness,
    outcome: "Assemble the complete evidence record required before finished work can be released through Creation Rights.",
    ecosystem: ["Creation Rights", "C2PA", "Content Credentials"],
    tags: ["release", "proof", "evidence", "governance", "Creation Rights", "provenance"],
    preview: "This pack defines the evidence assembly process that confirms all checks have been completed before work moves to release. It maps each required proof artifact to the Creation Rights fields that must be satisfied.",
  },
  {
    slug: "voice-and-localization",
    name: "Voice and Localization Skill Pack",
    category: "Voice",
    section: "featured",
    featured: true,
    image: cskillsImages.capabilities.rightsSafeProduction,
    outcome: "Define consent rules, persona protections, locale requirements, and evidence capture for voice and dubbed content.",
    ecosystem: ["ElevenLabs", "Dubbing tools", "Rights & NILP\u00AE"],
    tags: ["voice", "localization", "consent", "persona", "NILP", "dubbing", "likeness"],
    preview: "This pack defines how voice generation, cloning, and dubbing are used with full consent verification, persona protections, locale requirements, and evidence capture for every voice output.",
  },

  // === Image & Video ===
  {
    slug: "image-generation",
    name: "Image Generation Skill Pack",
    category: "Image",
    section: "image-video",
    featured: false,
    image: cskillsImages.capabilities.agentToolPlaybooks,
    outcome: "Define approved image generation from text or reference inputs with brand and rights checks at every stage.",
    ecosystem: ["fal.ai", "ComfyUI", "Midjourney", "Adobe Firefly"],
    tags: ["image", "generation", "brand", "rights", "model", "text-to-image"],
    preview: "This pack defines which image generation tools and models are approved, what reference inputs are allowed, what brand rules and rights checks apply at each stage, and what metadata must be returned with every generated image.",
  },
  {
    slug: "cutdown",
    name: "Cutdown Skill Pack",
    category: "Video",
    section: "image-video",
    featured: false,
    image: cskillsImages.engagements.operatingModelDesign,
    outcome: "Create format-specific cutdowns from approved masters with rights inheritance and talent usage scope.",
    ecosystem: ["Frame.io", "Adobe Premiere", "DaVinci Resolve"],
    tags: ["video", "cutdown", "post-production", "rights", "talent", "format"],
    preview: "This pack defines how cutdowns are created from approved master assets, what format and duration rules apply, how rights and talent usage scope are inherited, and what approvals are required before delivery.",
  },
  {
    slug: "ltx-video",
    name: "LTX Video Skill Pack",
    category: "Video",
    section: "image-video",
    featured: false,
    image: cskillsImages.engagements.pilotTransformation,
    outcome: "Define approved video generation and editing rules for LTX model infrastructure.",
    ecosystem: ["LTX Video", "LTX image-to-video", "LTX keyframe"],
    tags: ["video", "LTX", "generation", "keyframe", "model"],
    preview: "This pack defines approved use of LTX video generation models including text-to-video, image-to-video, and keyframe controls. It covers input constraints, output limits, brand checks, and evidence requirements specific to the LTX infrastructure.",
  },
  {
    slug: "comfyui-production",
    name: "ComfyUI Production Skill Pack",
    category: "Image",
    section: "image-video",
    featured: false,
    image: cskillsImages.engagements.governanceBlueprint,
    outcome: "Run approved ComfyUI pipelines with approved node lists, brand LoRAs, and evidence capture.",
    ecosystem: ["ComfyUI", "ControlNet", "IP-Adapter", "LoRA"],
    tags: ["image", "ComfyUI", "pipeline", "LoRA", "ControlNet", "nodes"],
    preview: "This pack defines which ComfyUI nodes and pipelines are approved, what LoRAs and adapters may be used, what brand constraints apply to outputs, and what evidence must be captured at each pipeline stage.",
  },
  {
    slug: "product-media",
    name: "Product Media Skill Pack",
    category: "Product Media",
    section: "image-video",
    featured: false,
    image: cskillsImages.capabilities.companyFlowDesign,
    outcome: "Generate product visuals and packaging renders under brand rules with evidence and metadata return.",
    ecosystem: ["ComfyUI", "fal.ai", "Adobe Firefly", "AEM Assets"],
    tags: ["product", "brand", "packaging", "render", "image", "metadata"],
    preview: "This pack defines how product visuals, packaging renders, and marketing assets are generated under strict brand rules. It covers approved source assets, brand profile alignment, metadata requirements, and delivery destinations.",
  },
  {
    slug: "fal-ai-model-access",
    name: "fal.ai Model Access Skill Pack",
    category: "Image",
    section: "image-video",
    featured: false,
    image: cskillsImages.engagements.agentOperatingBlueprint,
    outcome: "Access fal.ai model endpoints for approved image and video generation with approved endpoint lists.",
    ecosystem: ["fal.ai", "Flux", "SDXL", "Lightning models"],
    tags: ["image", "video", "fal.ai", "model", "endpoint", "generation"],
    preview: "This pack defines which fal.ai model endpoints are approved for use, what input constraints apply, what outputs are permitted, and how evidence and metadata are captured for each generation request.",
  },

  // === Audio, Voice & Localization ===
  {
    slug: "elevenlabs-voice-review",
    name: "ElevenLabs Voice Review Skill Pack",
    category: "Voice",
    section: "audio-voice",
    featured: false,
    image: cskillsImages.capabilities.executiveWorkshops,
    outcome: "Review and approve voice outputs with talent consent verification and persona protection checks.",
    ecosystem: ["ElevenLabs", "Voice cloning review", "Consent systems"],
    tags: ["voice", "ElevenLabs", "consent", "persona", "cloning", "review"],
    preview: "This pack defines how ElevenLabs voice outputs are reviewed and approved. It covers consent verification for voice cloning, persona protection checks, usage scope limits, and evidence capture for every voice generation.",
  },
  {
    slug: "localization",
    name: "Localization Skill Pack",
    category: "Localization",
    section: "audio-voice",
    featured: false,
    image: cskillsImages.capabilities.implementationSupport,
    outcome: "Localize content across languages and markets with cultural review, consent per locale, and rights scope.",
    ecosystem: ["Dubbing tools", "Translation systems", "DDEX"],
    tags: ["localization", "translation", "dubbing", "locale", "consent", "cultural"],
    preview: "This pack defines how content is localized across languages and markets. It covers cultural review requirements, consent verification per locale, rights scope constraints, metadata standards, and delivery rules for each target market.",
  },

  // === Asset, Metadata & Review ===
  {
    slug: "dam-handoff",
    name: "DAM Handoff Skill Pack",
    category: "Metadata",
    section: "asset-metadata",
    featured: false,
    image: cskillsImages.engagements.implementationOffice,
    outcome: "Define the handoff of approved work to DAM systems with full metadata and evidence records.",
    ecosystem: ["AEM Assets", "Bynder", "S3", "Internal DAM/MAM"],
    tags: ["DAM", "handoff", "metadata", "asset", "delivery", "evidence"],
    preview: "This pack defines how approved work is handed off to DAM and MAM systems. It covers metadata validation, evidence attachment, naming conventions, taxonomy alignment, and confirmation records for each handoff.",
  },
  {
    slug: "metadata-enrichment",
    name: "Metadata Enrichment Skill Pack",
    category: "Metadata",
    section: "asset-metadata",
    featured: false,
    image: cskillsImages.engagements.review,
    outcome: "Enrich asset metadata for searchability, rights tracking, and release readiness with schema validation.",
    ecosystem: ["IPTC", "C2PA", "Content Credentials", "DDEX"],
    tags: ["metadata", "IPTC", "C2PA", "provenance", "schema", "enrichment"],
    preview: "This pack defines how asset metadata is enriched for searchability, rights tracking, and release readiness. It covers required fields, schema validation rules, provenance standards, and Creation Rights field mapping.",
  },
  {
    slug: "frame-io-review",
    name: "Frame.io Review Skill Pack",
    category: "Video",
    section: "asset-metadata",
    featured: false,
    image: cskillsImages.audiences.agencies,
    outcome: "Define approved review and approval routing with escalation rules and evidence capture.",
    ecosystem: ["Frame.io", "Creative review tools"],
    tags: ["review", "approval", "Frame.io", "routing", "escalation", "video"],
    preview: "This pack defines how creative review and approval routing works through Frame.io. It covers review triggers, escalation paths, approval records, evidence capture, and handoff rules once work is approved.",
  },
  {
    slug: "aem-assets-readiness",
    name: "AEM Assets Readiness Skill Pack",
    category: "Metadata",
    section: "asset-metadata",
    featured: false,
    image: cskillsImages.audiences.enterpriseCreativeOps,
    outcome: "Prepare finished work for approved ingestion into Adobe Experience Manager with metadata alignment.",
    ecosystem: ["Adobe AEM Assets", "Metadata mapping", "Taxonomy"],
    tags: ["AEM", "asset", "metadata", "taxonomy", "ingestion", "Adobe"],
    preview: "This pack defines how finished work is prepared for ingestion into Adobe Experience Manager. It covers metadata alignment, taxonomy mapping, naming conventions, and validation checks required before ingestion.",
  },
  {
    slug: "archive-reuse",
    name: "Archive Reuse Skill Pack",
    category: "Archive Reuse",
    section: "asset-metadata",
    featured: false,
    image: cskillsImages.audiences.brands,
    outcome: "Access and reuse archived assets with rights verification, re-consent checks, and provenance tracking.",
    ecosystem: ["AEM Assets", "Bynder", "Internal DAM/MAM"],
    tags: ["archive", "reuse", "rights", "consent", "provenance", "asset"],
    preview: "This pack defines how archived assets are accessed and reused. It covers rights verification, re-consent checks for talent and likeness, provenance tracking, and evidence requirements before archived work enters new production.",
  },

  // === Rights, Proof & Release ===
  {
    slug: "brand-review",
    name: "Brand Review Skill Pack",
    category: "Brand Review",
    section: "rights-release",
    featured: false,
    image: cskillsImages.audiences.studiosMedia,
    outcome: "Run brand alignment checks against approved Brand Profiles with evidence and escalation paths.",
    ecosystem: ["Brand Profiles", "Creative review tools"],
    tags: ["brand", "review", "alignment", "Brand Profile", "escalation"],
    preview: "This pack defines how brand alignment checks are run against approved Brand Profiles. It covers tone, visual style, messaging constraints, escalation paths, and evidence capture for every brand review decision.",
  },
  {
    slug: "rights-and-nilp-check",
    name: "Rights & NILP\u00AE Check Skill Pack",
    category: "Rights & NILP\u00AE",
    section: "rights-release",
    featured: false,
    image: cskillsImages.capabilities.rightsSafeProduction,
    outcome: "Verify NILP\u00AE status, consent boundaries, and rights constraints before work moves forward.",
    ecosystem: ["Rights & NILP\u00AE", "Consent systems", "Creation Rights"],
    tags: ["rights", "NILP", "consent", "persona", "likeness", "name", "image"],
    preview: "This pack defines how NILP\u00AE (Name, Image, Likeness, and Persona) checks are run before work moves forward. It covers consent verification, usage scope, talent constraints, escalation rules, and evidence capture.",
  },
  {
    slug: "content-credentials",
    name: "Content Credentials Skill Pack",
    category: "Release",
    section: "rights-release",
    featured: false,
    image: cskillsImages.insights.creationRightsValue,
    outcome: "Attach content credentials and provenance data to outputs for verified distribution.",
    ecosystem: ["C2PA", "Content Credentials", "IPTC"],
    tags: ["provenance", "C2PA", "credentials", "release", "distribution", "metadata"],
    preview: "This pack defines how content credentials and provenance data are attached to finished outputs. It covers C2PA manifest creation, signing requirements, metadata embedding, and verification checks before distribution.",
  },
];

export const packCategories = [
  "All",
  "Image",
  "Video",
  "Audio",
  "Voice",
  "Localization",
  "Likeness",
  "Product Media",
  "Archive Reuse",
  "Metadata",
  "Brand Review",
  "Rights & NILP\u00AE",
  "Release",
] as const;

export type PackCategory = (typeof packCategories)[number];
