import { cskillsImages } from "./images";

export type SkillPackDetail = {
  slug: string;
  name: string;
  description: string;
  image: string;
  badges: string[];
  ecosystem: string[];
  overview: {
    enables: string;
    bestFor: string;
    clientOutcome: string;
  };
  definition: {
    action: string;
    tools: string;
    allowedAssets: string;
    restrictedAssets: string;
    brandRules: string;
    rightsRules: string;
    outputRules: string;
  };
  inputs: {
    sourceAssets: string[];
    referenceMaterials: string[];
    requiredMetadata: string[];
    accessLevel: string;
    destinations: string[];
  };
  rules: {
    approvalGates: string[];
    brandReview: string;
    rightsReview: string;
    escalation: string;
    blocked: string[];
  };
  evidence: string[];
  examples: {
    name: string;
    input: string;
    output: string;
    checks: string;
  }[];
  crChecks: string[];
};

export const skillPackDetails: SkillPackDetail[] = [
  // ===== PRIORITY FULL DETAIL PACKS =====
  {
    slug: "ai-video-generation",
    name: "AI Video Generation Skill Pack",
    description: "Defines approved use of video generation tools, source assets, likeness limits, review gates, evidence capture, and Creation Rights release checks.",
    image: cskillsImages.capabilities.productionAgentSkills,
    badges: ["Video", "Model-assisted creation", "Sample Pack", "Client setup available", "Creation Rights ready"],
    ecosystem: ["Runway", "LTX", "fal.ai", "ComfyUI", "Adobe Firefly"],
    overview: {
      enables: "Approved video generation from text prompts, image inputs, or video-to-video transformations using client-approved models. Teams can produce at scale while maintaining brand alignment, rights protections, and full evidence capture.",
      bestFor: "Creative teams, production studios, and brand teams producing video content using generative models and needing full governance from brief to release.",
      clientOutcome: "A complete operating file that defines which video models your team can use, what inputs are allowed, what approval gates apply, what evidence is captured, and what Creation Rights checks before release.",
    },
    definition: {
      action: "Generate, edit, or transform video assets using approved generative models within defined brand and rights boundaries.",
      tools: "LTX Video, Runway Gen-3, fal.ai video endpoints, ComfyUI AnimateDiff, Adobe Firefly Motion. Client-approved model list only.",
      allowedAssets: "Source briefs, storyboards, reference frames, brand motion templates, approved audio guides, product photography for video-from-image.",
      restrictedAssets: "Unlicensed reference footage, competitor brand assets, talent imagery without consent, assets from non-approved libraries.",
      brandRules: "All outputs must pass Brand Profile motion check. Tone, pacing, color grading, and visual language must match approved motion guidelines.",
      rightsRules: "NILP\u00AE review required for any output containing recognizable likeness, voice, or persona elements. Consent verification before render.",
      outputRules: "Minimum 1080p resolution. Metadata must include model ID, prompt hash, generation parameters, and timestamp. Maximum 60s per generation without escalation.",
    },
    inputs: {
      sourceAssets: ["Approved storyboards", "Reference frames from brand library", "Product photography", "Audio reference tracks", "Motion style guides"],
      referenceMaterials: ["Brand motion guidelines", "Tone and pacing references", "Color grading LUTs", "Previous approved outputs"],
      requiredMetadata: ["Brief ID", "Campaign reference", "Target format and duration", "Intended distribution channel"],
      accessLevel: "Production team with creative lead oversight. Model access restricted to approved endpoint list.",
      destinations: ["Internal review system", "Frame.io for approval", "DAM for approved outputs", "Release pipeline"],
    },
    rules: {
      approvalGates: ["Creative lead review before any external use", "Brand sign-off on first output per campaign", "Rights check before render if talent-adjacent", "Final approval before release pipeline entry"],
      brandReview: "Automated Brand Profile motion check on all outputs. Manual review for edge cases or new visual territory. Escalation to brand lead for contested outputs.",
      rightsReview: "NILP\u00AE scan for likeness, voice, or persona elements. Consent verification against rights database. Usage scope confirmation per talent agreement.",
      escalation: "Any output flagged by NILP\u00AE check escalates to rights team. Contested brand outputs escalate to brand lead. Unresolved items escalate to legal.",
      blocked: ["Generation of recognizable individuals without consent", "Use of non-approved models", "Outputs exceeding licensed territory scope", "Content that violates brand tone guidelines", "Generation from unlicensed reference material"],
    },
    evidence: [
      "Source asset references and brief ID",
      "Prompt or instruction text (hashed)",
      "Model ID and version used",
      "Generation parameters and seed",
      "Render timestamp and duration",
      "Reviewer identity and approval status",
      "Brand Profile check result",
      "NILP\u00AE check result",
      "Metadata schema compliance",
      "Output file hash and format",
      "Release destination assignment",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Product launch video from storyboard",
        input: "6-frame storyboard + brand motion guide + product photography",
        output: "15s product video at 1080p with brand-compliant motion and color",
        checks: "Brand Profile pass, no NILP\u00AE flags, metadata complete, approved for social release",
      },
      {
        name: "Localized campaign cutdown",
        input: "Approved master video + locale brief + translated overlay text",
        output: "9:16 vertical cutdown with localized text and adapted pacing",
        checks: "Rights inheritance confirmed, locale review passed, talent consent valid for territory",
      },
      {
        name: "Product demo from reference frames",
        input: "Product photos + motion style reference + script outline",
        output: "30s product demonstration video with branded transitions",
        checks: "No talent likeness, Brand Profile pass, product claims review cleared",
      },
    ],
    crChecks: [
      "Brand Profile match confirmed",
      "Rights & NILP\u00AE rules satisfied",
      "Approved tool/model from permitted list",
      "Metadata schema complete and validated",
      "All approval gates completed",
      "Evidence artifacts saved and linked",
      "Release Proof assembled",
      "Release Manifest populated",
      "Release Destination rules confirmed",
      "Protected Record created",
    ],
  },
  {
    slug: "voice-and-localization",
    name: "Voice and Localization Skill Pack",
    description: "Defines consent rules, persona protections, locale requirements, and evidence capture for voice and dubbed content.",
    image: cskillsImages.capabilities.rightsSafeProduction,
    badges: ["Voice", "Persona protection", "Localization", "Sample Pack", "Creation Rights ready"],
    ecosystem: ["ElevenLabs", "Dubbing tools", "Translation systems", "DDEX", "Rights & NILP\u00AE"],
    overview: {
      enables: "Approved voice generation, cloning, dubbing, and localization with full consent verification, persona protection, and evidence capture across languages and markets.",
      bestFor: "Teams producing voiced content, dubbed outputs, or localized assets where talent consent, persona rights, and cultural review are critical.",
      clientOutcome: "A complete operating file that defines which voice tools your team can use, what consent must be verified, what persona protections apply, and what evidence is captured per locale.",
    },
    definition: {
      action: "Generate, clone, adapt, or dub voice content using approved providers within defined consent and persona boundaries.",
      tools: "ElevenLabs, Azure TTS, Play.ht, dubbing platforms, translation memory systems. Client-approved voice providers only.",
      allowedAssets: "Approved scripts, talent reference recordings with valid consent, locale specifications, cultural guidelines, music and audio metadata references.",
      restrictedAssets: "Voice recordings without consent, persona elements from non-consenting talent, assets exceeding territorial rights scope.",
      brandRules: "Voice tone and delivery must match Brand Profile audio guidelines. Cultural sensitivity review required per market. Consistency check across locales.",
      rightsRules: "NILP\u00AE persona check required for all voice outputs. Consent boundary verification per talent agreement. Usage scope confirmation per territory.",
      outputRules: "Audio quality minimum standards per format. Metadata must include voice model ID, consent record reference, locale version, and talent attribution.",
    },
    inputs: {
      sourceAssets: ["Approved scripts per locale", "Talent voice profiles with consent", "Reference recordings", "Cultural guidelines per market", "Pronunciation guides"],
      referenceMaterials: ["Brand audio guidelines", "Previous approved voice outputs", "Talent agreements and consent records", "Market-specific tone references"],
      requiredMetadata: ["Script version", "Target locale", "Talent consent reference", "Campaign and brief ID"],
      accessLevel: "Voice team with rights oversight. Voice model access restricted to consented profiles only.",
      destinations: ["Internal review for quality", "Cultural sensitivity review", "DAM for approved audio", "Video assembly pipeline"],
    },
    rules: {
      approvalGates: ["Talent consent verification before generation", "Persona review on all cloned outputs", "Cultural sensitivity check per locale", "Rights team sign-off before external use"],
      brandReview: "Brand audio tone check against approved voice guidelines. Delivery pace and emotion alignment review. Cross-locale consistency check.",
      rightsReview: "Consent validity verification against talent agreement. Persona boundary check for voice cloning outputs. Territory scope confirmation per locale.",
      escalation: "Any persona concern escalates to rights team immediately. Cultural sensitivity flags escalate to market lead. Consent gaps escalate to legal.",
      blocked: ["Voice cloning without explicit talent consent", "Persona use exceeding agreement scope", "Generation for territories not covered by consent", "Outputs that misrepresent talent identity"],
    },
    evidence: [
      "Script version and locale identifier",
      "Voice model ID and provider",
      "Talent consent record reference",
      "Persona check result",
      "Cultural review status",
      "Generation parameters",
      "Reviewer identity and approval",
      "Locale adaptation log",
      "Territory scope confirmation",
      "Output quality validation",
      "Metadata schema compliance",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Product voiceover in 5 locales",
        input: "Approved English script + 5 locale translations + brand voice profile",
        output: "5 voiced audio files matching brand tone with locale-specific pacing",
        checks: "Talent consent valid for all territories, persona check clear, cultural review passed",
      },
      {
        name: "Voice clone for brand character",
        input: "Consented talent recording + character brief + script",
        output: "Character voiceover with consistent persona across campaign",
        checks: "Explicit consent on file, persona boundaries respected, usage scope within agreement",
      },
    ],
    crChecks: [
      "Brand Profile audio match confirmed",
      "Rights & NILP\u00AE persona check passed",
      "Talent consent valid and in scope",
      "Approved voice provider from permitted list",
      "Metadata complete per locale",
      "All approval gates completed",
      "Evidence artifacts saved per territory",
      "Release Proof assembled",
      "Release Manifest populated with locale data",
      "Protected Record created per territory",
    ],
  },
  {
    slug: "metadata-enrichment",
    name: "Metadata Enrichment Skill Pack",
    description: "Defines metadata schema requirements, provenance fields, and validation rules for assets before release or archive.",
    image: cskillsImages.engagements.review,
    badges: ["Metadata", "Provenance", "Sample Pack", "Client setup available", "Creation Rights ready"],
    ecosystem: ["IPTC", "C2PA", "Content Credentials", "DDEX", "DAM/MAM systems"],
    overview: {
      enables: "Approved metadata enrichment across assets with schema validation, provenance chain integrity, and release readiness verification before handoff to DAM or release systems.",
      bestFor: "Teams managing large asset libraries who need consistent metadata standards, provenance tracking, and Creation Rights field population across all output types.",
      clientOutcome: "A complete operating file that defines your metadata schema requirements, validation rules, provenance fields, and the enrichment checks every asset must pass before release.",
    },
    definition: {
      action: "Enrich, validate, and complete metadata fields on assets using approved schemas and taxonomy systems.",
      tools: "Metadata schema validators, tagging tools, taxonomy systems, IPTC writing tools, C2PA signing. Client metadata stack.",
      allowedAssets: "All assets in production or post-production requiring metadata enrichment before release, archive, or handoff.",
      restrictedAssets: "Assets without clear provenance chain. Assets from unauthorized sources. Outputs that have bypassed approval gates.",
      brandRules: "Metadata must reference the Brand Profile applied. Category and taxonomy values must align with brand information architecture.",
      rightsRules: "Rights fields must reflect current consent status. NILP\u00AE status per element. Expiry dates and territory restrictions must be populated.",
      outputRules: "All required schema fields must be populated. Provenance chain must be intact. Validation score must meet minimum threshold before handoff.",
    },
    inputs: {
      sourceAssets: ["Assets pending metadata enrichment", "Existing partial metadata records", "Provenance chain data", "Taxonomy references"],
      referenceMaterials: ["Client metadata schema documentation", "IPTC field mapping", "C2PA assertion templates", "Taxonomy hierarchy"],
      requiredMetadata: ["Asset origin", "Creation method", "Tools used", "Rights status", "Approval state"],
      accessLevel: "Metadata team with schema owner oversight. Write access to metadata fields on approved assets only.",
      destinations: ["DAM system for enriched assets", "Archive for completed records", "Release pipeline for validated outputs"],
    },
    rules: {
      approvalGates: ["Schema owner validation on new field definitions", "Quality spot-check on enriched batches", "Completeness verification before handoff"],
      brandReview: "Category taxonomy alignment check. Brand Profile reference validation. Information architecture compliance.",
      rightsReview: "Rights field accuracy verification. Consent status currency check. Territory and expiry date validation.",
      escalation: "Schema validation failures escalate to metadata lead. Rights field conflicts escalate to rights team. Provenance gaps escalate for investigation.",
      blocked: ["Writing metadata on assets without clear provenance", "Overwriting rights fields without authorization", "Releasing assets with incomplete required fields"],
    },
    evidence: [
      "Asset identifier and version",
      "Schema version applied",
      "Fields enriched (list)",
      "Validation status and score",
      "Provenance chain integrity check",
      "Rights fields populated and verified",
      "Taxonomy alignment confirmed",
      "Completeness score",
      "Enrichment timestamp",
      "Operator or system identity",
      "Quality check result",
      "Creation Rights handoff readiness",
    ],
    examples: [
      {
        name: "Batch enrichment for product photography",
        input: "200 product images with partial metadata + schema template",
        output: "Complete metadata records with IPTC fields, provenance, and rights status",
        checks: "Schema validation 100%, provenance intact, rights fields current, ready for DAM handoff",
      },
      {
        name: "C2PA credential attachment",
        input: "Final approved video + provenance assertions + signing certificate",
        output: "Video with embedded C2PA manifest and content credentials",
        checks: "Credential chain valid, provenance complete, release authorized",
      },
    ],
    crChecks: [
      "Metadata schema fully populated",
      "Provenance chain intact and verified",
      "Rights fields current and accurate",
      "Brand Profile reference validated",
      "NILP\u00AE status fields populated",
      "All approval gates completed",
      "Evidence of enrichment saved",
      "Release Proof metadata section complete",
      "Release Manifest fields mapped",
      "Protected Record metadata layer ready",
    ],
  },
  {
    slug: "dam-handoff",
    name: "DAM Handoff Skill Pack",
    description: "Defines handoff rules for moving approved work into DAM systems with full metadata, evidence records, and release status.",
    image: cskillsImages.engagements.implementationOffice,
    badges: ["Asset systems", "Handoff governance", "Sample Pack", "Client setup available", "Creation Rights ready"],
    ecosystem: ["AEM Assets", "Bynder", "S3", "Internal DAM/MAM"],
    overview: {
      enables: "Approved handoff to DAM and MAM systems with full metadata validation, evidence chain confirmation, and release status verification before ingestion.",
      bestFor: "Teams with large asset libraries who need structured handoff rules, naming conventions, folder hierarchies, and metadata completeness checks before assets enter their DAM.",
      clientOutcome: "A complete operating file that defines your DAM handoff rules, metadata requirements, naming conventions, folder structures, and the validation checks every asset must pass before ingestion.",
    },
    definition: {
      action: "Validate, package, and hand off approved assets to DAM systems with complete metadata and evidence records.",
      tools: "Bynder, Adobe AEM Assets, Canto, Brandfolder, S3. Client DAM system and ingestion APIs.",
      allowedAssets: "Release-approved outputs with complete metadata records, evidence chains, and approval confirmations.",
      restrictedAssets: "Assets without release approval. Assets with incomplete metadata. Assets missing evidence records. Draft or work-in-progress files.",
      brandRules: "Naming conventions must follow brand information architecture. Folder placement must align with approved taxonomy. Asset variants must reference parent.",
      rightsRules: "Rights status must be confirmed before handoff. Territory restrictions must be encoded in metadata. Expiry dates must be set where applicable.",
      outputRules: "All required DAM fields must be populated. File format must match destination requirements. Naming convention must be validated. Evidence chain must be linked.",
    },
    inputs: {
      sourceAssets: ["Release-approved files", "Complete metadata records", "Evidence chain artifacts", "Approval confirmation records"],
      referenceMaterials: ["DAM taxonomy documentation", "Naming convention rules", "Folder hierarchy map", "Required field mapping"],
      requiredMetadata: ["Asset title", "Category", "Rights status", "Territory scope", "Expiry date", "Creator attribution", "Approval chain"],
      accessLevel: "DAM operations team with admin oversight. Write access to approved ingestion folders only.",
      destinations: ["Primary DAM system", "Archive storage", "CDN for distribution-ready assets", "Backup and redundancy systems"],
    },
    rules: {
      approvalGates: ["Metadata completeness verification", "Evidence chain confirmation", "DAM admin acceptance", "Post-ingestion validation"],
      brandReview: "Naming convention compliance check. Taxonomy placement validation. Parent-variant relationship verification.",
      rightsReview: "Rights status confirmation at time of handoff. Territory encoding validation. Expiry date verification.",
      escalation: "Metadata validation failures return to production team. Rights status conflicts escalate to rights team. Ingestion errors escalate to DAM admin.",
      blocked: ["Handoff of unapproved assets", "Assets with incomplete metadata", "Files without evidence chain", "Assets exceeding territory or time scope"],
    },
    evidence: [
      "Asset identifier and file hash",
      "Handoff manifest (full field list)",
      "Metadata validation record",
      "DAM ingestion confirmation",
      "Naming convention check result",
      "Folder placement validation",
      "Rights status at handoff time",
      "Evidence chain link confirmation",
      "Approval chain reference",
      "Post-ingestion verification",
      "Distribution readiness status",
      "Creation Rights handoff complete",
    ],
    examples: [
      {
        name: "Campaign asset batch handoff",
        input: "48 approved campaign assets + metadata records + evidence artifacts",
        output: "Assets ingested in DAM with correct taxonomy, naming, and linked evidence",
        checks: "Metadata 100% complete, rights confirmed, evidence linked, taxonomy correct",
      },
      {
        name: "Product photography refresh",
        input: "New product images + updated metadata + supersedes records",
        output: "New assets ingested, old versions archived with relationship links preserved",
        checks: "Version relationships maintained, rights current, old assets marked superseded",
      },
    ],
    crChecks: [
      "Release status confirmed before handoff",
      "Metadata schema fully validated",
      "Evidence chain complete and linked",
      "Rights status current and encoded",
      "Brand taxonomy compliance verified",
      "All approval gates satisfied",
      "Handoff manifest generated",
      "Release Manifest updated with destination",
      "DAM ingestion confirmed",
      "Protected Record updated with handoff status",
    ],
  },
  {
    slug: "rights-and-nilp-check",
    name: "Rights & NILP\u00AE Check Skill Pack",
    description: "Defines how NILP\u00AE (Name, Image, Likeness, and Persona) constraints are verified, consent is confirmed, and rights status is checked before work moves forward.",
    image: cskillsImages.capabilities.rightsSafeProduction,
    badges: ["Rights", "NILP\u00AE", "Persona protection", "Sample Pack", "Creation Rights ready"],
    ecosystem: ["Rights & NILP\u00AE", "Consent systems", "Creation Rights"],
    overview: {
      enables: "Verification of NILP\u00AE status, consent boundaries, and rights constraints across all outputs containing talent, likeness, voice, or persona elements.",
      bestFor: "Teams producing content that includes talent, voice actors, brand ambassadors, or any persona elements requiring consent verification and rights protection.",
      clientOutcome: "A complete operating file that defines your NILP\u00AE check process, consent verification steps, rights database requirements, escalation paths, and the evidence captured at each stage.",
    },
    definition: {
      action: "Verify NILP\u00AE status, confirm consent boundaries, check rights constraints, and produce evidence of verification before work can proceed to release.",
      tools: "Rights database, consent management system, NILP\u00AE verification checks, talent agreement references. Client rights infrastructure.",
      allowedAssets: "All outputs containing recognizable talent, likeness, voice, or persona elements requiring rights verification.",
      restrictedAssets: "Outputs where talent has not consented. Assets exceeding territorial or temporal scope. Content using persona elements beyond agreement boundaries.",
      brandRules: "Talent usage must align with brand positioning. Persona representation must match brand guidelines. No unauthorized association between talent and brand claims.",
      rightsRules: "Every element containing Name, Image, Likeness, or Persona must be individually verified. Consent must be current, in-scope, and documented. Territory and time restrictions must be confirmed.",
      outputRules: "NILP\u00AE status must be recorded per element. Consent chain must be documented. Rights expiry dates must be set. Verification evidence must be saved.",
    },
    inputs: {
      sourceAssets: ["Outputs pending rights review", "Talent agreements and consent records", "Previous NILP\u00AE check results", "Usage scope documentation"],
      referenceMaterials: ["Talent agreement database", "Consent record system", "Territory and time scope references", "Brand representation guidelines"],
      requiredMetadata: ["Talent identifier", "Asset identifier", "Intended use scope", "Target territories", "Intended duration"],
      accessLevel: "Rights team with legal oversight. Read access to consent records and talent agreements. Write access to NILP\u00AE status fields.",
      destinations: ["Approved assets pipeline (if passed)", "Hold queue (if flagged)", "Legal escalation (if contested)", "Evidence storage"],
    },
    rules: {
      approvalGates: ["Initial NILP\u00AE scan on all outputs with talent elements", "Consent verification against talent agreement", "Usage scope confirmation per territory and time", "Rights team sign-off on contested or edge cases"],
      brandReview: "Talent-brand association review. Persona representation alignment check. No unauthorized claims or endorsement implications.",
      rightsReview: "Consent validity and currency check. Territory scope verification. Time scope verification. Usage type confirmation against agreement terms.",
      escalation: "Any element without clear consent escalates immediately. Expired agreements escalate to rights team. Contested persona use escalates to legal. Territory conflicts require market-specific review.",
      blocked: ["Use of talent without documented consent", "Persona elements exceeding agreement scope", "Content in territories not covered by rights", "Outputs after consent expiry date", "Unauthorized likeness manipulation or combination"],
    },
    evidence: [
      "Talent identifier per element",
      "NILP\u00AE status (Name, Image, Likeness, Persona) per element",
      "Consent record reference and validity date",
      "Territory scope confirmed",
      "Time scope confirmed",
      "Usage type matched to agreement",
      "Reviewer identity and sign-off",
      "Escalation record (if applicable)",
      "Rights database query timestamp",
      "Verification result (pass/flag/block)",
      "Evidence artifacts saved",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Campaign video with brand ambassador",
        input: "60s video featuring signed ambassador + campaign brief + territory list",
        output: "NILP\u00AE verified: consent valid, territory scope confirmed, persona use within agreement",
        checks: "Consent current, 12 territories confirmed, likeness use within scope, no manipulation",
      },
      {
        name: "Generated content with likeness elements",
        input: "Generated image referencing talent style + consent documentation",
        output: "NILP\u00AE flagged: likeness boundary review required before release",
        checks: "Escalated to rights team, likeness threshold assessment, legal confirmation required",
      },
      {
        name: "Voice clone consent verification",
        input: "Cloned voice output + original talent consent + usage scope",
        output: "NILP\u00AE verified: persona consent valid for stated use and territories",
        checks: "Voice consent explicit, persona boundary respected, territory and time confirmed",
      },
    ],
    crChecks: [
      "NILP\u00AE status confirmed per element",
      "Consent validity verified and current",
      "Territory scope matches intended distribution",
      "Time scope within agreement boundaries",
      "Usage type approved per talent agreement",
      "No unauthorized likeness manipulation",
      "All escalations resolved",
      "Evidence of verification saved",
      "Release Proof NILP\u00AE section complete",
      "Protected Record persona layer ready",
    ],
  },
  {
    slug: "release-proof",
    name: "Release Proof Skill Pack",
    description: "Defines the evidence assembly process that confirms all checks have been completed before finished work can be released through Creation Rights.",
    image: cskillsImages.core.creationRightsReadiness,
    badges: ["Release", "Governance", "Evidence assembly", "Sample Pack", "Creation Rights ready"],
    ecosystem: ["Creation Rights", "C2PA", "Content Credentials"],
    overview: {
      enables: "Structured assembly of the complete evidence record required before any finished work can be released. Maps each required proof artifact to the Creation Rights fields that must be satisfied.",
      bestFor: "Operations teams responsible for final release approval who need a clear, repeatable process for confirming that all brand, rights, metadata, and evidence requirements have been met.",
      clientOutcome: "A complete operating file that defines your release proof structure, required evidence artifacts, validation checks, sign-off requirements, and the Creation Rights fields each proof satisfies.",
    },
    definition: {
      action: "Assemble, validate, and confirm the complete evidence record for a piece of work before it enters the release pipeline.",
      tools: "Evidence management systems, metadata validators, C2PA signing tools, release management systems. Client release infrastructure.",
      allowedAssets: "Finished work that has completed all prior approval gates and carries complete metadata and evidence records.",
      restrictedAssets: "Work-in-progress outputs. Assets with incomplete approval chains. Outputs missing required evidence artifacts. Content with unresolved rights flags.",
      brandRules: "Release proof must confirm Brand Profile alignment was verified. Brand sign-off record must be present. Any brand exceptions must be documented.",
      rightsRules: "Release proof must confirm NILP\u00AE checks completed. Consent status must be current at release time. Territory and time scope must be validated against intended distribution.",
      outputRules: "Release proof must be complete before any work enters the release pipeline. All required fields must be populated. Sign-off chain must be documented.",
    },
    inputs: {
      sourceAssets: ["Finished approved work", "Evidence artifacts from production", "Approval chain records", "Metadata validation results", "Rights check confirmations"],
      referenceMaterials: ["Release proof template", "Required evidence checklist", "Creation Rights field mapping", "Sign-off authority matrix"],
      requiredMetadata: ["Asset ID", "Campaign reference", "All prior approval records", "Evidence artifact references", "Intended release destinations"],
      accessLevel: "Release operations team with legal and brand oversight. Read access to all evidence records. Write access to release proof fields.",
      destinations: ["Release pipeline (if proof complete)", "Hold queue (if proof incomplete)", "Escalation (if contested)", "Protected Records archive"],
    },
    rules: {
      approvalGates: ["Evidence completeness verification", "Metadata validation confirmation", "Rights status currency check", "Final sign-off from release authority"],
      brandReview: "Confirmation that Brand Profile check was passed and documented. Verification that brand sign-off is present in the evidence chain.",
      rightsReview: "Confirmation that NILP\u00AE checks passed. Verification that consent is current. Territory and time validation against release plan.",
      escalation: "Missing evidence artifacts return to production team. Rights concerns escalate to legal. Brand exceptions escalate to brand lead. Incomplete proofs cannot proceed.",
      blocked: ["Release of work without complete proof", "Missing NILP\u00AE verification", "Expired consent at release time", "Incomplete metadata", "Unsigned approval chains"],
    },
    evidence: [
      "Release proof document (complete)",
      "Evidence artifact inventory",
      "All prior approval records linked",
      "Brand Profile check confirmation",
      "NILP\u00AE verification status",
      "Consent currency at release time",
      "Metadata validation score",
      "Territory scope confirmation",
      "Release authority sign-off",
      "Proof assembly timestamp",
      "Release destination assignment",
      "Protected Record creation status",
    ],
    examples: [
      {
        name: "Campaign video release proof",
        input: "Approved 30s video + 14 evidence artifacts + approval chain + metadata record",
        output: "Complete release proof with all Creation Rights fields satisfied",
        checks: "Brand pass, NILP\u00AE clear, consent current, metadata complete, 3 sign-offs confirmed",
      },
      {
        name: "Product image batch release",
        input: "48 approved product images + batch evidence record + rights confirmations",
        output: "Batch release proof confirming all items meet release criteria",
        checks: "Schema 100%, no rights flags, brand alignment confirmed, evidence complete per item",
      },
      {
        name: "Localized asset release across territories",
        input: "12 locale versions + per-territory consent records + cultural review results",
        output: "Per-territory release proofs with locale-specific evidence",
        checks: "Consent valid per territory, cultural reviews passed, metadata complete per locale",
      },
    ],
    crChecks: [
      "All evidence artifacts present and linked",
      "Brand Profile alignment documented",
      "Rights & NILP\u00AE verification confirmed",
      "Consent current at time of release",
      "Metadata schema complete",
      "All prior approval gates satisfied",
      "Release authority sign-off recorded",
      "Release Manifest ready for population",
      "Destination rules confirmed",
      "Protected Record created with full proof",
    ],
  },

  // ===== LIGHTER PREVIEW PACKS =====
  {
    slug: "image-generation",
    name: "Image Generation Skill Pack",
    description: "Defines approved image generation from text or reference inputs with brand and rights checks at every stage.",
    image: cskillsImages.capabilities.agentToolPlaybooks,
    badges: ["Image", "Model-assisted creation", "Sample Pack"],
    ecosystem: ["fal.ai", "ComfyUI", "Midjourney", "Adobe Firefly"],
    overview: {
      enables: "Approved image generation using text prompts or reference inputs with brand alignment, rights protection, and evidence capture at each stage.",
      bestFor: "Creative and brand teams producing image content at scale who need clear rules for which tools, inputs, and brand constraints apply.",
      clientOutcome: "An operating file that defines which image generation tools your team can use, what inputs are allowed, what brand checks apply, and what evidence is captured.",
    },
    definition: {
      action: "Generate or transform images using approved models within defined brand and rights boundaries.",
      tools: "fal.ai endpoints, ComfyUI pipelines, Midjourney, Adobe Firefly. Client-approved model list only.",
      allowedAssets: "Source briefs, reference imagery from brand library, product photography, style guides, approved prompts.",
      restrictedAssets: "Competitor brand assets, unlicensed reference imagery, talent photos without consent.",
      brandRules: "All outputs must pass Brand Profile visual check. Color, typography, composition, and style must match approved guidelines.",
      rightsRules: "NILP\u00AE review required if outputs contain recognizable likeness. Source asset rights must be confirmed before use as reference.",
      outputRules: "Minimum resolution per format. Metadata must include model ID, prompt reference, and generation timestamp.",
    },
    inputs: {
      sourceAssets: ["Reference imagery from brand library", "Product photography", "Style guides"],
      referenceMaterials: ["Brand visual guidelines", "Color and typography standards", "Previous approved outputs"],
      requiredMetadata: ["Brief ID", "Target format", "Intended use channel"],
      accessLevel: "Creative team with brand lead oversight.",
      destinations: ["Internal review", "DAM for approved outputs", "Release pipeline"],
    },
    rules: {
      approvalGates: ["Brand visual check on all outputs", "Rights check if likeness adjacent", "Final approval before external use"],
      brandReview: "Automated Brand Profile visual check. Manual review for new visual territory.",
      rightsReview: "NILP\u00AE scan for likeness elements. Source asset rights verification.",
      escalation: "Likeness flags escalate to rights team. Brand disputes escalate to brand lead.",
      blocked: ["Use of non-approved models", "Generation from unlicensed references", "Outputs without brand check"],
    },
    evidence: [
      "Prompt or instruction reference",
      "Model ID and version",
      "Generation parameters",
      "Brand Profile check result",
      "NILP\u00AE check result (if applicable)",
      "Reviewer approval",
      "Output file hash",
      "Metadata schema compliance",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Product hero image generation",
        input: "Product photo + brand style guide + format specification",
        output: "Hero image at required resolution matching brand visual language",
        checks: "Brand Profile pass, no likeness flags, metadata complete",
      },
    ],
    crChecks: [
      "Brand Profile match confirmed",
      "Rights & NILP\u00AE rules satisfied",
      "Approved model from permitted list",
      "Metadata schema validated",
      "Approval gates completed",
      "Evidence saved",
      "Release Proof assembled",
      "Protected Record created",
    ],
  },
  {
    slug: "cutdown",
    name: "Cutdown Skill Pack",
    description: "Defines how format-specific cutdowns are created from approved masters with rights inheritance and talent usage scope.",
    image: cskillsImages.engagements.operatingModelDesign,
    badges: ["Video", "Post-production", "Sample Pack"],
    ecosystem: ["Frame.io", "Adobe Premiere", "DaVinci Resolve"],
    overview: {
      enables: "Approved creation of format-specific cutdowns from master assets with automatic rights inheritance, talent usage scope verification, and evidence capture.",
      bestFor: "Production teams creating multi-format deliverables from approved master content across channels and markets.",
      clientOutcome: "An operating file that defines which formats are approved, how rights and talent usage scope are inherited, and what approvals apply to each cutdown.",
    },
    definition: {
      action: "Create format-specific cutdowns from approved master assets within defined rights and talent boundaries.",
      tools: "Adobe Premiere, DaVinci Resolve, Frame.io for review. Client post-production tools.",
      allowedAssets: "Approved master assets with confirmed rights status. Brand-approved overlay elements and lower thirds.",
      restrictedAssets: "Unapproved masters. Assets with expired rights. Talent content exceeding usage scope.",
      brandRules: "Format and duration must match approved specifications. Pacing and edit style must align with brand motion guidelines.",
      rightsRules: "Talent usage scope must be verified per cutdown format and territory. Rights inheritance from master must be confirmed.",
      outputRules: "Format specifications per channel. Rights inheritance record required. Evidence of master approval must be linked.",
    },
    inputs: {
      sourceAssets: ["Approved master video", "Format specifications", "Channel requirements"],
      referenceMaterials: ["Brand motion guidelines", "Channel format specs", "Territory distribution plan"],
      requiredMetadata: ["Master asset reference", "Target format", "Target channel", "Territory scope"],
      accessLevel: "Post-production team with creative lead oversight.",
      destinations: ["Frame.io for review", "DAM for approved cutdowns", "Distribution systems"],
    },
    rules: {
      approvalGates: ["Master approval confirmed before work begins", "Creative lead review on first cutdown per format", "Rights inheritance check per territory"],
      brandReview: "Format compliance check. Pacing and edit style alignment with brand guidelines.",
      rightsReview: "Talent usage scope verification per format. Territory rights confirmation per cutdown.",
      escalation: "Talent scope concerns escalate to rights team. Format disputes escalate to creative lead.",
      blocked: ["Cutdowns from unapproved masters", "Talent use exceeding agreement scope", "Distribution to non-approved territories"],
    },
    evidence: [
      "Master asset reference",
      "Cutdown format and duration",
      "Rights inheritance confirmation",
      "Talent scope verification",
      "Reviewer approval",
      "Brand check result",
      "Output file reference",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Social format cutdowns from campaign master",
        input: "Approved 60s master + 3 format specs (9:16, 1:1, 16:9)",
        output: "3 cutdowns matching format specs with inherited rights",
        checks: "Rights inherited, talent scope valid for all formats, brand guidelines met",
      },
    ],
    crChecks: [
      "Master approval confirmed",
      "Rights inheritance documented",
      "Talent scope verified per format",
      "Brand alignment checked",
      "Metadata complete per cutdown",
      "Evidence saved",
      "Release Proof assembled",
      "Protected Record created",
    ],
  },
  {
    slug: "ltx-video",
    name: "LTX Video Skill Pack",
    description: "Defines approved video generation and editing rules for LTX model infrastructure.",
    image: cskillsImages.engagements.pilotTransformation,
    badges: ["Video", "Model-assisted creation", "Sample Pack"],
    ecosystem: ["LTX Video", "LTX image-to-video", "LTX keyframe"],
    overview: {
      enables: "Approved use of LTX video generation models including text-to-video, image-to-video, and keyframe controls with brand alignment and evidence capture.",
      bestFor: "Teams using LTX infrastructure for video generation who need clear rules for inputs, outputs, and quality checks.",
      clientOutcome: "An operating file defining approved LTX model use, input constraints, output rules, and evidence requirements specific to your LTX deployment.",
    },
    definition: {
      action: "Generate or edit video using LTX models within approved input and output boundaries.",
      tools: "LTX Video (text-to-video), LTX image-to-video, LTX keyframe control. Approved LTX endpoints only.",
      allowedAssets: "Approved prompts, reference frames, keyframe guides, product photography for video generation.",
      restrictedAssets: "Talent imagery without consent, competitor references, assets from non-approved sources.",
      brandRules: "Outputs must match brand motion guidelines. Color and visual style must align with Brand Profile.",
      rightsRules: "NILP\u00AE check required if likeness elements are present. Source asset rights must be confirmed.",
      outputRules: "Resolution and format per specification. Metadata must include model version, seed, and parameters.",
    },
    inputs: {
      sourceAssets: ["Text prompts", "Reference frames", "Keyframe guides", "Product photography"],
      referenceMaterials: ["Brand motion guidelines", "LTX model documentation", "Output format specs"],
      requiredMetadata: ["Model version", "Generation parameters", "Brief reference"],
      accessLevel: "Production team with approved LTX endpoint access.",
      destinations: ["Internal review", "Post-production pipeline", "DAM for approved outputs"],
    },
    rules: {
      approvalGates: ["Creative review on outputs", "Brand check before external use", "Rights check if likeness adjacent"],
      brandReview: "Brand motion guidelines alignment. Visual style compliance.",
      rightsReview: "NILP\u00AE scan if likeness elements present. Source rights verification.",
      escalation: "Likeness concerns escalate to rights team. Quality issues return to production.",
      blocked: ["Use of non-approved LTX endpoints", "Generation from unlicensed references", "Outputs without review"],
    },
    evidence: [
      "Model version and endpoint",
      "Prompt or input reference",
      "Generation parameters and seed",
      "Brand check result",
      "Reviewer approval",
      "Output file reference",
      "Metadata compliance",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Product video from keyframe reference",
        input: "3 keyframes + motion style guide + brand color palette",
        output: "10s product video matching keyframe progression and brand style",
        checks: "Brand alignment confirmed, no likeness elements, metadata complete",
      },
    ],
    crChecks: [
      "Approved LTX endpoint used",
      "Brand Profile match confirmed",
      "NILP\u00AE check completed (if applicable)",
      "Metadata validated",
      "Approval gates completed",
      "Evidence saved",
      "Release Proof assembled",
      "Protected Record created",
    ],
  },
  {
    slug: "comfyui-production",
    name: "ComfyUI Production Skill Pack",
    description: "Defines approved ComfyUI pipelines with permitted node lists, brand LoRAs, and evidence capture at each stage.",
    image: cskillsImages.engagements.governanceBlueprint,
    badges: ["Image", "Pipeline governance", "Sample Pack"],
    ecosystem: ["ComfyUI", "ControlNet", "IP-Adapter", "LoRA"],
    overview: {
      enables: "Approved ComfyUI pipeline execution with permitted node lists, brand-trained LoRAs, and structured evidence capture at each generation stage.",
      bestFor: "Teams running ComfyUI for production image generation who need clear rules for which nodes, LoRAs, and pipeline configurations are approved.",
      clientOutcome: "An operating file defining approved ComfyUI nodes, permitted LoRAs, pipeline structures, and evidence requirements for your production environment.",
    },
    definition: {
      action: "Execute image generation pipelines using approved ComfyUI configurations and permitted model components.",
      tools: "ComfyUI with approved node list. ControlNet, IP-Adapter, LoRA. Client-approved pipeline configurations only.",
      allowedAssets: "Approved brand LoRAs, reference imagery from brand library, product photography, style guides.",
      restrictedAssets: "Non-approved nodes or extensions, untested LoRAs, unlicensed training data references.",
      brandRules: "Only brand-approved LoRAs may be loaded. Outputs must pass Brand Profile visual check.",
      rightsRules: "LoRA training data provenance must be documented. NILP\u00AE check if likeness-trained models used.",
      outputRules: "Resolution per format spec. Full pipeline state captured. Metadata includes node graph hash and LoRA versions.",
    },
    inputs: {
      sourceAssets: ["Reference imagery", "Brand LoRA models", "Pipeline configuration files"],
      referenceMaterials: ["Approved node list", "Brand LoRA documentation", "Pipeline structure templates"],
      requiredMetadata: ["Pipeline version", "Node graph hash", "LoRA versions used"],
      accessLevel: "Production team with approved ComfyUI environment access.",
      destinations: ["Internal review", "Quality check pipeline", "DAM for approved outputs"],
    },
    rules: {
      approvalGates: ["Node list compliance check", "LoRA approval verification", "Brand visual check on outputs"],
      brandReview: "Automated Brand Profile check on all outputs. LoRA alignment verification.",
      rightsReview: "LoRA provenance verification. NILP\u00AE check for likeness-adjacent models.",
      escalation: "Unapproved node use blocks pipeline. LoRA provenance gaps escalate for review.",
      blocked: ["Non-approved nodes", "Untested LoRAs", "Pipelines without evidence capture"],
    },
    evidence: [
      "Pipeline configuration hash",
      "Node graph state",
      "LoRA versions and provenance",
      "Generation parameters",
      "Brand check result",
      "Output file reference",
      "Metadata compliance",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Product imagery via brand LoRA pipeline",
        input: "Product photo + brand LoRA + style reference + pipeline config",
        output: "Product hero image matching brand style with full pipeline evidence",
        checks: "Approved nodes only, brand LoRA valid, Brand Profile pass, metadata complete",
      },
    ],
    crChecks: [
      "Approved nodes and LoRAs only",
      "Brand Profile match confirmed",
      "LoRA provenance documented",
      "Metadata validated",
      "Approval gates completed",
      "Pipeline evidence saved",
      "Release Proof assembled",
      "Protected Record created",
    ],
  },
  {
    slug: "product-media",
    name: "Product Media Skill Pack",
    description: "Defines how product visuals and packaging renders are generated under brand rules with evidence and metadata return.",
    image: cskillsImages.capabilities.companyFlowDesign,
    badges: ["Product Media", "Brand-controlled", "Sample Pack"],
    ecosystem: ["ComfyUI", "fal.ai", "Adobe Firefly", "AEM Assets"],
    overview: {
      enables: "Approved generation of product visuals, packaging renders, and marketing assets under strict brand rules with full evidence and metadata capture.",
      bestFor: "Brand and product teams generating product imagery at scale who need clear rules for visual consistency, brand alignment, and metadata return.",
      clientOutcome: "An operating file defining how product visuals are generated, what brand rules apply, what metadata must be returned, and where approved outputs are delivered.",
    },
    definition: {
      action: "Generate product visuals and packaging renders using approved tools within strict brand boundaries.",
      tools: "ComfyUI, fal.ai, Adobe Firefly, product rendering pipelines. Client-approved tools only.",
      allowedAssets: "Product photography, CAD renders, brand templates, approved background assets, packaging specifications.",
      restrictedAssets: "Competitor product references, unapproved background imagery, non-brand color palettes.",
      brandRules: "All outputs must match product brand guidelines exactly. Color accuracy, composition, and styling must follow brand specifications.",
      rightsRules: "Product imagery ownership must be confirmed. No third-party elements without license verification.",
      outputRules: "Format and resolution per channel spec. Metadata must include product SKU, variant, and generation method.",
    },
    inputs: {
      sourceAssets: ["Product photography or CAD renders", "Brand templates", "Packaging specifications"],
      referenceMaterials: ["Product brand guidelines", "Channel format specifications", "Color accuracy standards"],
      requiredMetadata: ["Product SKU", "Variant", "Target channel", "Campaign reference"],
      accessLevel: "Product creative team with brand lead oversight.",
      destinations: ["Brand review queue", "AEM Assets for approved outputs", "E-commerce systems"],
    },
    rules: {
      approvalGates: ["Brand visual accuracy check", "Product claims review", "Final approval before channel delivery"],
      brandReview: "Product brand guideline compliance. Color accuracy verification. Composition and styling check.",
      rightsReview: "Product imagery ownership confirmation. Third-party element license check.",
      escalation: "Brand accuracy failures return to production. Claims concerns escalate to legal.",
      blocked: ["Outputs not matching brand specifications", "Unapproved product claims in imagery", "Delivery without metadata"],
    },
    evidence: [
      "Product SKU and variant",
      "Generation method and tools used",
      "Brand check result",
      "Product claims review",
      "Metadata compliance",
      "Output file reference",
      "Approval record",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "E-commerce product hero images",
        input: "Product photos + brand templates + 4 channel format specs",
        output: "4 format variants per product matching brand guidelines exactly",
        checks: "Brand accuracy pass, color within tolerance, metadata complete per variant",
      },
    ],
    crChecks: [
      "Brand guidelines match confirmed",
      "Product claims verified",
      "Ownership confirmed",
      "Metadata complete per variant",
      "Approval gates completed",
      "Evidence saved",
      "Release Proof assembled",
      "Protected Record created",
    ],
  },
  {
    slug: "fal-ai-model-access",
    name: "fal.ai Model Access Skill Pack",
    description: "Defines which fal.ai model endpoints are approved for image and video generation with evidence capture.",
    image: cskillsImages.engagements.agentOperatingBlueprint,
    badges: ["Image", "Video", "Model access", "Sample Pack"],
    ecosystem: ["fal.ai", "Flux", "SDXL", "Lightning models"],
    overview: {
      enables: "Approved access to fal.ai model endpoints for image and video generation with defined input constraints, output rules, and evidence capture.",
      bestFor: "Teams using fal.ai infrastructure who need an approved endpoint list, input rules, and evidence capture for every generation request.",
      clientOutcome: "An operating file defining which fal.ai endpoints are approved, what inputs are allowed, what output checks apply, and how evidence is captured.",
    },
    definition: {
      action: "Access approved fal.ai model endpoints for image and video generation within defined boundaries.",
      tools: "fal.ai Flux, SDXL, Lightning, and video endpoints. Client-approved endpoint list only.",
      allowedAssets: "Text prompts, reference images from brand library, style guides, product photography.",
      restrictedAssets: "Non-approved endpoints, unlicensed reference material, prompts referencing protected personas.",
      brandRules: "Outputs must pass Brand Profile check. Prompt guidelines must be followed.",
      rightsRules: "NILP\u00AE check on outputs if persona-adjacent prompts used. No protected likeness generation.",
      outputRules: "Resolution per format spec. Metadata includes endpoint ID, model version, and parameters.",
    },
    inputs: {
      sourceAssets: ["Text prompts", "Reference images", "Style guides"],
      referenceMaterials: ["Approved endpoint list", "Prompt guidelines", "Brand visual standards"],
      requiredMetadata: ["Endpoint ID", "Model version", "Generation parameters"],
      accessLevel: "Production team with approved fal.ai API access.",
      destinations: ["Internal review", "Post-production pipeline", "DAM for approved outputs"],
    },
    rules: {
      approvalGates: ["Endpoint approval verification", "Brand check on outputs", "Rights check if persona-adjacent"],
      brandReview: "Brand Profile visual alignment check on all outputs.",
      rightsReview: "NILP\u00AE scan if prompts reference protected personas or likeness.",
      escalation: "Non-approved endpoint use is blocked. Persona flags escalate to rights team.",
      blocked: ["Non-approved endpoints", "Protected persona generation", "Outputs without evidence capture"],
    },
    evidence: [
      "Endpoint ID and model version",
      "Prompt or input reference",
      "Generation parameters",
      "Brand check result",
      "NILP\u00AE check (if applicable)",
      "Output file reference",
      "Metadata compliance",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Campaign imagery via approved Flux endpoint",
        input: "Creative brief + prompt + brand style reference",
        output: "Campaign image at target resolution via approved Flux endpoint",
        checks: "Approved endpoint confirmed, Brand Profile pass, metadata complete",
      },
    ],
    crChecks: [
      "Approved endpoint used",
      "Brand Profile match confirmed",
      "NILP\u00AE check completed (if applicable)",
      "Metadata validated",
      "Approval gates completed",
      "Evidence saved",
      "Release Proof assembled",
      "Protected Record created",
    ],
  },
  {
    slug: "elevenlabs-voice-review",
    name: "ElevenLabs Voice Review Skill Pack",
    description: "Defines how ElevenLabs voice outputs are reviewed and approved with consent verification and persona protection checks.",
    image: cskillsImages.capabilities.executiveWorkshops,
    badges: ["Voice", "Consent governance", "Sample Pack"],
    ecosystem: ["ElevenLabs", "Voice cloning review", "Consent systems"],
    overview: {
      enables: "Structured review and approval of ElevenLabs voice outputs with talent consent verification, persona protection checks, and evidence capture.",
      bestFor: "Teams using ElevenLabs for voice generation and cloning who need clear consent verification, persona checks, and approval paths.",
      clientOutcome: "An operating file defining how ElevenLabs outputs are reviewed, what consent checks apply, what persona protections are enforced, and what evidence is captured.",
    },
    definition: {
      action: "Review and approve ElevenLabs voice outputs with consent verification and persona boundary enforcement.",
      tools: "ElevenLabs platform, consent management system, voice review tools. Client voice infrastructure.",
      allowedAssets: "Scripts, consented voice profiles, character briefs, brand audio guidelines.",
      restrictedAssets: "Voice profiles without consent, persona elements exceeding agreement, non-approved voice models.",
      brandRules: "Voice tone must match Brand Profile audio guidelines. Delivery style must align with brand persona.",
      rightsRules: "Consent must be verified before any voice generation. Persona boundaries must be confirmed per use.",
      outputRules: "Audio quality standards per format. Metadata includes voice profile ID, consent reference, and generation parameters.",
    },
    inputs: {
      sourceAssets: ["Approved scripts", "Consented voice profiles", "Character briefs"],
      referenceMaterials: ["Brand audio guidelines", "Talent consent agreements", "Persona boundary documentation"],
      requiredMetadata: ["Voice profile ID", "Consent reference", "Script version", "Target use"],
      accessLevel: "Voice team with rights oversight. Access restricted to consented profiles.",
      destinations: ["Review queue", "Approved audio library", "Video assembly pipeline"],
    },
    rules: {
      approvalGates: ["Consent verification before generation", "Persona boundary check on outputs", "Quality review before delivery"],
      brandReview: "Brand audio tone alignment. Delivery style check against brand persona guidelines.",
      rightsReview: "Consent validity and scope confirmation. Persona boundary verification.",
      escalation: "Consent concerns escalate to rights team. Persona boundary questions escalate to legal.",
      blocked: ["Generation without consent", "Persona use beyond agreement", "Delivery without review"],
    },
    evidence: [
      "Voice profile ID and provider",
      "Consent record reference",
      "Persona boundary check result",
      "Generation parameters",
      "Quality review record",
      "Brand tone check result",
      "Output file reference",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Brand character voiceover review",
        input: "Script + consented voice profile + brand audio guidelines",
        output: "Approved voiceover matching brand tone with consent confirmed",
        checks: "Consent valid, persona within bounds, brand tone aligned, metadata complete",
      },
    ],
    crChecks: [
      "Consent verified and current",
      "Persona boundaries respected",
      "Brand audio guidelines met",
      "Approved voice profile used",
      "Metadata validated",
      "Evidence saved",
      "Release Proof assembled",
      "Protected Record created",
    ],
  },
  {
    slug: "localization",
    name: "Localization Skill Pack",
    description: "Defines how content is localized across languages and markets with cultural review, consent per locale, and rights scope.",
    image: cskillsImages.capabilities.implementationSupport,
    badges: ["Localization", "Multi-market", "Sample Pack"],
    ecosystem: ["Dubbing tools", "Translation systems", "DDEX"],
    overview: {
      enables: "Approved localization across languages and markets with cultural review, per-locale consent verification, rights scope confirmation, and metadata standards.",
      bestFor: "Teams localizing content across multiple markets who need clear rules for cultural review, consent per territory, and delivery standards.",
      clientOutcome: "An operating file defining your localization rules, cultural review requirements, consent verification per locale, and metadata standards per market.",
    },
    definition: {
      action: "Localize content across languages and markets with cultural review and rights verification per territory.",
      tools: "Translation memory systems, dubbing platforms, subtitle tools, cultural review systems. Client localization stack.",
      allowedAssets: "Approved master content, translation briefs, cultural guidelines per market, locale-specific assets.",
      restrictedAssets: "Masters without release approval, content for territories without rights, culturally inappropriate material.",
      brandRules: "Localized versions must maintain brand consistency while respecting cultural adaptation needs.",
      rightsRules: "Rights scope must be verified per territory. Talent consent must cover each target locale. Cultural sensitivity review required.",
      outputRules: "Quality standards per locale. Metadata must include locale identifier, territory scope, and cultural review status.",
    },
    inputs: {
      sourceAssets: ["Approved master content", "Translation briefs", "Cultural guidelines per market"],
      referenceMaterials: ["Territory rights documentation", "Cultural adaptation guidelines", "Brand consistency standards"],
      requiredMetadata: ["Source locale", "Target locale", "Territory rights scope", "Campaign reference"],
      accessLevel: "Localization team with cultural reviewers and rights oversight.",
      destinations: ["Cultural review queue", "Per-locale approval", "DAM with locale tagging", "Distribution per territory"],
    },
    rules: {
      approvalGates: ["Cultural review per locale", "Rights scope verification per territory", "Quality review before delivery"],
      brandReview: "Brand consistency check across locales. Cultural adaptation within brand boundaries.",
      rightsReview: "Territory rights scope verification. Talent consent per locale confirmation.",
      escalation: "Cultural sensitivity concerns escalate to market lead. Rights gaps escalate to legal.",
      blocked: ["Localization for territories without rights", "Content without cultural review", "Delivery without quality check"],
    },
    evidence: [
      "Source and target locale",
      "Cultural review status",
      "Territory rights confirmation",
      "Talent consent per locale",
      "Quality review record",
      "Brand consistency check",
      "Output file reference per locale",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Campaign localization to 8 markets",
        input: "Approved English master + 8 locale briefs + cultural guidelines",
        output: "8 localized versions with cultural adaptations and per-territory metadata",
        checks: "Cultural review passed per locale, rights confirmed per territory, quality standards met",
      },
    ],
    crChecks: [
      "Rights verified per territory",
      "Consent confirmed per locale",
      "Cultural review passed",
      "Brand consistency maintained",
      "Metadata complete per locale",
      "Evidence saved per territory",
      "Release Proof per locale assembled",
      "Protected Record per territory created",
    ],
  },
  {
    slug: "frame-io-review",
    name: "Frame.io Review Skill Pack",
    description: "Defines approved review and approval routing through Frame.io with escalation rules and evidence capture.",
    image: cskillsImages.audiences.agencies,
    badges: ["Review", "Approval routing", "Sample Pack"],
    ecosystem: ["Frame.io", "Creative review tools"],
    overview: {
      enables: "Structured review and approval routing through Frame.io with defined escalation paths, approval records, and evidence capture at each review stage.",
      bestFor: "Teams using Frame.io for creative review who need clear routing rules, escalation paths, and approval documentation.",
      clientOutcome: "An operating file defining your Frame.io review routing, approval paths, escalation rules, and evidence capture requirements.",
    },
    definition: {
      action: "Route creative work through Frame.io review with defined approval paths and evidence capture.",
      tools: "Frame.io, creative review integrations, approval management systems. Client review infrastructure.",
      allowedAssets: "Work-in-progress assets requiring review, approved references for comparison, review briefs.",
      restrictedAssets: "Assets bypassing review queue, outputs without proper routing, unapproved reviewer access.",
      brandRules: "Review criteria must reference Brand Profile requirements. Feedback must be documented against brand standards.",
      rightsRules: "Rights-adjacent content must be flagged for rights team review. Talent content must be routed to rights check.",
      outputRules: "Approval status must be recorded. Review history must be preserved. Escalation records must be linked.",
    },
    inputs: {
      sourceAssets: ["Work requiring review", "Review briefs", "Reference assets for comparison"],
      referenceMaterials: ["Review criteria documentation", "Routing rules", "Escalation matrix"],
      requiredMetadata: ["Project reference", "Review stage", "Required reviewers", "Deadline"],
      accessLevel: "Review team with project-specific access. Escalation access for leads and rights team.",
      destinations: ["Approved assets queue", "Revision queue", "Escalation queue", "Evidence archive"],
    },
    rules: {
      approvalGates: ["Initial routing to correct reviewers", "Feedback completion by all required parties", "Final approval sign-off"],
      brandReview: "Brand alignment assessment against defined criteria. Feedback documented against brand standards.",
      rightsReview: "Rights team routing for talent-adjacent content. NILP\u00AE flag routing.",
      escalation: "Contested feedback escalates to creative lead. Rights concerns escalate immediately. Missed deadlines escalate to project lead.",
      blocked: ["Bypassing required reviewers", "Releasing without all approvals", "Skipping rights routing for flagged content"],
    },
    evidence: [
      "Review routing record",
      "Reviewer comments and feedback",
      "Approval status per reviewer",
      "Escalation records (if any)",
      "Final sign-off",
      "Review timestamp",
      "Revision history",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Campaign video review cycle",
        input: "V2 cut + review brief + 3 required reviewers",
        output: "Approved with documented feedback, 2 revision notes resolved, brand pass confirmed",
        checks: "All reviewers signed off, no rights flags, escalation resolved, evidence complete",
      },
    ],
    crChecks: [
      "All required reviewers approved",
      "Brand criteria satisfied",
      "Rights routing completed (if flagged)",
      "Escalations resolved",
      "Review evidence preserved",
      "Approval chain documented",
      "Release Proof review section complete",
      "Protected Record updated",
    ],
  },
  {
    slug: "aem-assets-readiness",
    name: "AEM Assets Readiness Skill Pack",
    description: "Defines how finished work is prepared for approved ingestion into Adobe Experience Manager with metadata alignment.",
    image: cskillsImages.audiences.enterpriseCreativeOps,
    badges: ["Asset systems", "Platform prep", "Sample Pack"],
    ecosystem: ["Adobe AEM Assets", "Metadata mapping", "Taxonomy"],
    overview: {
      enables: "Structured preparation of finished work for ingestion into Adobe Experience Manager with metadata alignment, taxonomy mapping, and validation checks.",
      bestFor: "Teams using AEM Assets who need clear rules for metadata requirements, taxonomy alignment, and validation before ingestion.",
      clientOutcome: "An operating file defining your AEM ingestion requirements, metadata mapping, taxonomy rules, and validation checks.",
    },
    definition: {
      action: "Prepare finished work for AEM Assets ingestion with metadata alignment and taxonomy compliance.",
      tools: "Adobe AEM Assets, metadata mapping tools, taxonomy management. Client AEM environment.",
      allowedAssets: "Approved finished work with complete metadata, evidence records, and release status.",
      restrictedAssets: "Work-in-progress assets, outputs with incomplete metadata, assets without approval chain.",
      brandRules: "Taxonomy placement must follow brand information architecture. Naming must follow brand conventions.",
      rightsRules: "Rights fields must be populated and current before ingestion. Territory and expiry must be set.",
      outputRules: "All AEM required fields populated. Format requirements met. Taxonomy placement validated.",
    },
    inputs: {
      sourceAssets: ["Approved finished work", "Complete metadata records", "Evidence chain records"],
      referenceMaterials: ["AEM taxonomy documentation", "Required field mapping", "Naming conventions"],
      requiredMetadata: ["All AEM required fields", "Rights status", "Territory scope", "Expiry dates"],
      accessLevel: "DAM operations with AEM admin oversight.",
      destinations: ["AEM Assets (approved folders)", "AEM Archive", "CDN for published assets"],
    },
    rules: {
      approvalGates: ["Metadata completeness check", "Taxonomy alignment validation", "AEM admin acceptance"],
      brandReview: "Taxonomy placement and naming convention compliance.",
      rightsReview: "Rights field population and currency verification.",
      escalation: "Validation failures return to production. Taxonomy questions escalate to information architecture team.",
      blocked: ["Ingestion with incomplete metadata", "Assets without approval chain", "Non-compliant naming"],
    },
    evidence: [
      "AEM ingestion record",
      "Metadata validation result",
      "Taxonomy placement confirmation",
      "Naming convention check",
      "Rights field verification",
      "Admin acceptance record",
      "Post-ingestion validation",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Campaign assets AEM ingestion",
        input: "32 approved assets + metadata records + AEM taxonomy mapping",
        output: "Assets ingested in correct AEM folders with validated metadata",
        checks: "All fields populated, taxonomy correct, naming compliant, rights current",
      },
    ],
    crChecks: [
      "Metadata complete and validated",
      "Taxonomy alignment confirmed",
      "Rights fields current",
      "Naming conventions followed",
      "Approval chain documented",
      "Evidence linked",
      "AEM ingestion confirmed",
      "Protected Record updated",
    ],
  },
  {
    slug: "archive-reuse",
    name: "Archive Reuse Skill Pack",
    description: "Defines how archived assets are accessed and reused with rights verification, re-consent checks, and provenance tracking.",
    image: cskillsImages.audiences.brands,
    badges: ["Archive", "Rights verification", "Sample Pack"],
    ecosystem: ["AEM Assets", "Bynder", "Internal DAM/MAM"],
    overview: {
      enables: "Approved access and reuse of archived assets with rights re-verification, consent currency checks, and provenance tracking before archived work enters new production.",
      bestFor: "Teams reusing archived content who need clear rules for rights verification, consent re-confirmation, and provenance documentation.",
      clientOutcome: "An operating file defining your archive reuse rules, rights re-verification process, consent checks, and evidence requirements.",
    },
    definition: {
      action: "Access and verify archived assets for reuse with rights confirmation and provenance documentation.",
      tools: "DAM/MAM search, rights database, consent verification systems. Client archive infrastructure.",
      allowedAssets: "Archived assets with documented provenance and rights history. Assets with current or renewable rights.",
      restrictedAssets: "Assets with expired non-renewable rights. Content with withdrawn consent. Assets with unclear provenance.",
      brandRules: "Reused assets must still meet current Brand Profile requirements. Outdated brand elements must be flagged.",
      rightsRules: "Rights must be re-verified at time of reuse. Consent must be confirmed as current. Territory and time scope must be checked against new intended use.",
      outputRules: "Provenance chain must be maintained. Reuse record must link to original. New metadata must be appended.",
    },
    inputs: {
      sourceAssets: ["Archived assets identified for reuse", "Original rights records", "Original evidence chain"],
      referenceMaterials: ["Current Brand Profile", "Rights re-verification checklist", "Consent currency requirements"],
      requiredMetadata: ["Original asset ID", "New intended use", "Target territories", "New campaign reference"],
      accessLevel: "Production team with archive access and rights team oversight.",
      destinations: ["Active production pipeline (if rights confirmed)", "Hold queue (if re-consent needed)", "Rejection (if rights expired)"],
    },
    rules: {
      approvalGates: ["Rights re-verification", "Consent currency check", "Brand alignment with current standards", "Provenance chain confirmation"],
      brandReview: "Current Brand Profile alignment check. Outdated brand element identification.",
      rightsReview: "Full rights re-verification. Consent currency confirmation. Territory and time scope for new use.",
      escalation: "Expired rights block reuse. Consent questions escalate to rights team. Provenance gaps require investigation.",
      blocked: ["Reuse of expired-rights content", "Assets with withdrawn consent", "Content with unclear provenance", "Use beyond original scope without renewal"],
    },
    evidence: [
      "Original asset reference",
      "Rights re-verification result",
      "Consent currency confirmation",
      "Territory scope for new use",
      "Brand alignment check",
      "Provenance chain documentation",
      "Reuse authorization record",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Campaign reuse of archive photography",
        input: "12 archived product photos + new campaign brief + territory list",
        output: "8 assets cleared for reuse (4 flagged: rights expired for 2, consent lapsed for 2)",
        checks: "Rights confirmed for 8, re-consent initiated for 2, 2 blocked permanently",
      },
    ],
    crChecks: [
      "Rights re-verified for new use",
      "Consent confirmed as current",
      "Territory scope valid",
      "Provenance chain maintained",
      "Brand alignment confirmed",
      "Reuse authorization recorded",
      "Evidence of re-verification saved",
      "Protected Record updated with reuse",
    ],
  },
  {
    slug: "brand-review",
    name: "Brand Review Skill Pack",
    description: "Defines how brand alignment checks are run against approved Brand Profiles with evidence and escalation paths.",
    image: cskillsImages.audiences.studiosMedia,
    badges: ["Brand", "Review governance", "Sample Pack"],
    ecosystem: ["Brand Profiles", "Creative review tools"],
    overview: {
      enables: "Structured brand alignment checks against approved Brand Profiles with documented evidence, escalation paths, and sign-off records.",
      bestFor: "Teams producing creative output that must align with documented Brand Profiles and need clear review criteria, escalation rules, and evidence capture.",
      clientOutcome: "An operating file defining your brand review process, Brand Profile check criteria, escalation paths, and evidence requirements.",
    },
    definition: {
      action: "Run brand alignment checks against approved Brand Profiles and produce documented review evidence.",
      tools: "Brand Profile documents, visual comparison tools, creative review platforms. Client brand infrastructure.",
      allowedAssets: "Creative outputs requiring brand alignment verification before approval or release.",
      restrictedAssets: "Outputs that have bypassed brand review. Assets claiming brand approval without documented check.",
      brandRules: "All criteria defined in the Brand Profile must be checked. Tone, visual style, messaging, and composition requirements apply.",
      rightsRules: "Brand representation must not imply unauthorized endorsements. Talent-brand associations must be within agreement scope.",
      outputRules: "Brand review result must be documented. Pass, flag, or fail status must be recorded with reasoning.",
    },
    inputs: {
      sourceAssets: ["Creative outputs pending brand review", "Brand Profile documents", "Previous approved references"],
      referenceMaterials: ["Brand Profile (tone, visual, messaging)", "Brand guidelines", "Approved reference examples"],
      requiredMetadata: ["Asset reference", "Campaign context", "Target audience", "Distribution channel"],
      accessLevel: "Brand review team with brand lead escalation access.",
      destinations: ["Approved queue (if pass)", "Revision queue (if flag)", "Rejection with notes (if fail)"],
    },
    rules: {
      approvalGates: ["Initial brand alignment assessment", "Detailed criteria check per Brand Profile section", "Brand lead sign-off on contested items"],
      brandReview: "Full Brand Profile check: tone, visual language, messaging, composition, color, typography. Each criterion documented.",
      rightsReview: "Endorsement implication check. Talent-brand association scope verification.",
      escalation: "Contested results escalate to brand lead. Repeated failures escalate to creative director. Endorsement concerns escalate to legal.",
      blocked: ["Release without brand review", "Outputs contradicting Brand Profile", "Unauthorized brand associations"],
    },
    evidence: [
      "Brand Profile version checked against",
      "Criteria assessment per section",
      "Pass/flag/fail status",
      "Reviewer identity and notes",
      "Escalation record (if any)",
      "Brand lead sign-off (if required)",
      "Revision history",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Campaign creative brand alignment",
        input: "6 campaign assets + Brand Profile v3.2 + channel context",
        output: "4 passed, 1 flagged (color deviation), 1 failed (tone mismatch)",
        checks: "Documented per criterion, flagged item revised and re-checked, failed item returned to creative",
      },
    ],
    crChecks: [
      "Brand Profile check completed",
      "All criteria documented",
      "Pass/flag/fail status recorded",
      "Escalations resolved",
      "Brand lead sign-off where required",
      "Evidence preserved",
      "Release Proof brand section complete",
      "Protected Record updated",
    ],
  },
  {
    slug: "content-credentials",
    name: "Content Credentials Skill Pack",
    description: "Defines how content credentials and provenance data are attached to finished outputs for verified distribution.",
    image: cskillsImages.insights.creationRightsValue,
    badges: ["Provenance", "Release prep", "Sample Pack"],
    ecosystem: ["C2PA", "Content Credentials", "IPTC"],
    overview: {
      enables: "Attachment of content credentials and provenance data to finished outputs with C2PA manifest creation, signing, and verification before distribution.",
      bestFor: "Teams preparing content for distribution who need verifiable provenance, content credentials, and trust signals attached to their outputs.",
      clientOutcome: "An operating file defining your content credentials process, signing requirements, manifest structure, and verification checks before distribution.",
    },
    definition: {
      action: "Create and attach content credentials with provenance assertions and signing to finished outputs.",
      tools: "C2PA signing tools, Content Credentials platforms, IPTC embedding tools. Client credential infrastructure.",
      allowedAssets: "Finished approved outputs ready for credential attachment and distribution.",
      restrictedAssets: "Work-in-progress assets, outputs without full approval chain, content with unresolved rights flags.",
      brandRules: "Credential assertions must align with brand claims. Provenance narrative must be accurate.",
      rightsRules: "Rights status must be confirmed before credential creation. Creator attribution must be accurate.",
      outputRules: "C2PA manifest must be valid and complete. Signing must use authorized certificate. Verification must pass.",
    },
    inputs: {
      sourceAssets: ["Finished approved outputs", "Provenance assertion data", "Signing certificates"],
      referenceMaterials: ["C2PA manifest templates", "Assertion requirements", "Signing authority documentation"],
      requiredMetadata: ["Creator attribution", "Creation method", "Tools used", "Rights status", "Approval chain"],
      accessLevel: "Release operations with signing authority access.",
      destinations: ["Distribution systems", "Archive with credentials", "Verification systems"],
    },
    rules: {
      approvalGates: ["Provenance data accuracy verification", "Signing authority confirmation", "Post-signing validation"],
      brandReview: "Credential assertions align with brand claims. No misleading provenance narrative.",
      rightsReview: "Rights status confirmed before signing. Creator attribution verified.",
      escalation: "Invalid assertions return for correction. Signing failures escalate to credential authority.",
      blocked: ["Signing unapproved content", "Invalid assertions", "Expired signing certificates", "Misleading provenance claims"],
    },
    evidence: [
      "C2PA manifest record",
      "Provenance assertions",
      "Signing certificate reference",
      "Signing timestamp",
      "Verification result",
      "Creator attribution",
      "Rights status at signing time",
      "Creation Rights handoff status",
    ],
    examples: [
      {
        name: "Campaign video credential attachment",
        input: "Approved 30s video + provenance data + signing certificate",
        output: "Video with embedded C2PA manifest, content credentials, and verified provenance chain",
        checks: "Manifest valid, assertions accurate, signing verified, provenance chain complete",
      },
    ],
    crChecks: [
      "Provenance data accurate",
      "Assertions verified",
      "Signing authority confirmed",
      "Manifest valid and complete",
      "Verification passed",
      "Rights confirmed at signing",
      "Evidence saved",
      "Protected Record updated with credentials",
    ],
  },
];
