// Auto-generated by designlang — component anatomy v2.
// Scaffolds. Wire into your token system; not a runtime library.

import * as React from 'react';

export interface CardProps {
  variant?: 'outline';
  size?: 'md';
  children?: React.ReactNode;
}

export function Card({ variant = 'outline', size = 'md', ...rest }: CardProps) {
  return React.createElement('div', { 'data-variant': variant, 'data-size': size, ...rest });
}

export interface ButtonProps {
  variant?: 'link';
  size?: 'small';
  children?: React.ReactNode;
}

export function Button({ variant = 'link', size = 'md', ...rest }: ButtonProps) {
  return React.createElement('button', { 'data-variant': variant, 'data-size': size, ...rest });
}
