// Framer Motion presets — generated by designlang (motionlang)
// Source: https://ltx.io
// 2026-06-03T02:30:26.199Z
//
//   import { transitions, variants } from './ltx.io-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeOut: [0.215, 0.61, 0.355, 1], // 28× on page
  custom2: [0.455, 0.03, 0.515, 0.955], // 26× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 4× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.1,
  sm: 0.2,
  md: 0.3,
  lg: 0.45,
  xl: 1.05,
  xxl: 2,
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.3, ease: easings.easeOut },
  fast:  { duration: 0.150, ease: easings.easeOut },
  slow:  { duration: 0.540, ease: easings.easeOut },
  spring: { type: 'spring', stiffness: 320, damping: 30 },
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.075 } },
  },
};

export default { easings, durations, transitions, variants };
