// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://ltx.io
// Generated: 2026-06-03T02:30:26.198Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#333333' | '#f9f9f9' | '#000000' | '#999999' | '#555555' | '#1f1f24' | '#0b0b0b' | '#dddddd' | '#0000ee' | '#3860be' | '#7d87a0' | '#f4f4f4' | '#2b61ff' | '#7a7c81' | '#2e3445' | '#0a7da4' | '#ff72b2' | '#003cf0' | '#636367' | '#32ae88' | '#468254' | '#d1d1d1' | '#bbbbbb';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Aeonik' | 'Miriam Libre' | 'Times' | 'Inconsolata' | 'Arial';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '700' | '300';

export type SpacingToken = '1px' | '35px' | '38px' | '48px' | '64px' | '72px' | '80px' | '192px' | '208px' | '245px' | '312px' | '367px' | '392px';

export type RadiusToken = '2px' | '8px' | '17px' | '20px' | '50px' | '100px' | '130px' | '800px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '450ms' | '1050ms' | '2000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
