export const routes = {
  home: "/",
  whatWeDo: "/what-we-do",
  engagements: "/engagements",
  engagement: (slug: string) => `/engagements/${slug}`,
  whoWeHelp: "/who-we-help",
  audience: (slug: string) => `/who-we-help/${slug}`,
  method: "/method",
  creationRightsReadiness: "/creation-rights-readiness",
  resources: "/resources",
  resource: (slug: string) => `/resources/${slug}`,
  about: "/about",
  bookReview: "/book-review",
  contact: "/contact",
  faq: "/faq",
  legal: "/legal",
  legalDocument: (region: string, slug: string) => `/legal/${region}/${slug}`,
  privacy: "/legal",
  terms: "/legal",
  cookies: "/legal",
  accessibility: "/accessibility",
  legalNotice: "/legal",
  thankYou: {
    review: "/thank-you/review",
    contact: "/thank-you/contact",
    partnership: "/thank-you/partnership",
    briefing: "/thank-you/briefing",
    newsletter: "/thank-you/newsletter",
  },
} as const;
